(()=>{const $=id=>document.getElementById(id),slots=['①','②','③','④','⑤','⑥','⑦','⑧','⑨','⑩','⑪'];const times=['13:30–14:10','14:20–15:00','15:10–15:50','16:00–16:40','16:50–17:30','17:40–18:20','18:30–19:10','19:20–20:00','20:10–20:50','21:00–21:40','21:50–22:30'];const arrivalTimes=['13:20','14:10','15:00','15:50','16:40','17:30','18:20','19:10','20:00','20:50','21:40'];let entries=[],days=[],matrix={},dirty=false;
function draw(){const mode=$('availabilityMode').value,esc=Workspace.esc;$('availabilityHelp').textContent=mode==='ok'?'チェックしたコマだけ勤務OKです。未チェックのコマはNGになります。':'チェックしたコマがNGです。未チェックのコマは勤務OKです。';$('availabilityGrid').innerHTML=`<table class="ws-table ng-matrix ${mode==='ok'?'ok-mode':''}"><thead><tr><th>日付</th>${slots.map((s,i)=>`<th scope="col">${s}<small class="ng-slot-time">${times[i]}</small><small class="ng-slot-arrival">（${arrivalTimes[i]}入）</small></th>`).join('')}<th>終日</th></tr></thead><tbody>`+days.map(date=>`<tr class="${date===Workspace.today()?'today':''}"><td>${date.slice(5)}（${['日','月','火','水','木','金','土'][new Date(date+'T00:00:00').getDay()]}）</td>${slots.map(s=>`<td><label><input type="checkbox" aria-label="${date} ${s} ${times[slots.indexOf(s)]} ${arrivalTimes[slots.indexOf(s)]}入 ${mode.toUpperCase()}" data-date="${date}" data-slot="${s}" ${(mode==='ng'?matrix[date].has(s):!matrix[date].has(s))?'checked':''}></label></td>`).join('')}<td><button class="ws-button" data-day="${date}">全コマ切替</button></td></tr>`).join('')+'</tbody></table>';}
async function load(){if(dirty&&!confirm('未保存の変更を取り消して、期間を読み直しますか？'))return;const j=await Workspace.api('teacher_ng_api.php');entries=j.entries||[];days=[];matrix={};const first=new Date($('availabilityStart').value+'T00:00:00');if(isNaN(first))return;for(let i=0;i<Number($('availabilityDays').value);i++){const d=new Date(first);d.setDate(d.getDate()+i);const date=d.toLocaleDateString('sv-SE');days.push(date);const e=entries.find(x=>x.teacher===$('availabilityTeacher').value&&x.date===date);matrix[date]=new Set(e?.allDay?slots:e?.slots||[]);}dirty=false;draw();}
StaffAuth.ready.then(async j=>{await Workspace.ready;const me=j.user;if(!me)return;let names=[me.name];if(me.role==='admin'){const [data,ng]=await Promise.all([Workspace.api('data_api.php'),Workspace.api('teacher_ng_api.php')]);names=[...new Set([me.name,...data.schedule.map(r=>r['担当講師']).filter(Boolean),...(ng.entries||[]).map(r=>r.teacher).filter(Boolean)])];}$('availabilityTeacher').innerHTML=names.map(n=>`<option>${Workspace.esc(n)}</option>`).join('');$('availabilityTeacher').disabled=me.role!=='admin';const params=new URLSearchParams(location.search),date=params.get('date')||'',teacher=params.get('teacher');const parsed=new Date(date+'T00:00:00');const valid=/^\d{4}-\d{2}-\d{2}$/.test(date)&&!isNaN(parsed)&&parsed.toLocaleDateString('sv-SE')===date;if(me.role==='admin'&&names.includes(teacher))$('availabilityTeacher').value=teacher;$('availabilityStart').value=valid?date:Workspace.today();await load();});
$('availabilityLoad').onclick=()=>load().catch(e=>$('availabilityMessage').textContent=e.message);$('availabilityTeacher').onchange=$('availabilityLoad').onclick;$('availabilityMode').onchange=draw;
$('availabilityGrid').onchange=e=>{const {date,slot}=e.target.dataset;if(!date)return;const ng=$('availabilityMode').value==='ng'?e.target.checked:!e.target.checked;ng?matrix[date].add(slot):matrix[date].delete(slot);dirty=true;};
$('availabilityGrid').onclick=e=>{const b=e.target.closest('[data-day]');if(!b)return;const set=matrix[b.dataset.day];matrix[b.dataset.day]=set.size===11?new Set():new Set(slots);dirty=true;draw();};
$('allUnavailable').onclick=()=>{days.forEach(d=>matrix[d]=new Set(slots));dirty=true;draw();};$('allAvailable').onclick=()=>{days.forEach(d=>matrix[d]=new Set());dirty=true;draw();};
$('availabilitySave').onclick=async e=>{e.target.disabled=true;try{const note=$('availabilityNote').value;const j=await Workspace.api('teacher_ng_api.php',{action:'grid',teacher:$('availabilityTeacher').value,days:days.map(date=>({date,slots:[...matrix[date]],note:note||entries.find(x=>x.teacher===$('availabilityTeacher').value&&x.date===date)?.note||''}))});dirty=false;$('availabilityMessage').textContent='保存しました。'+(j.notified?'直前の変更を管理者へ通知しました。':'');await load();}catch(err){$('availabilityMessage').textContent=err.message;}finally{e.target.disabled=false;}};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
})();
