(()=>{'use strict';
const preview=new URL(location.href).searchParams.get('preview')==='student';if(preview)document.body.classList.add('board-student-preview');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),uid=()=>crypto.randomUUID().replaceAll('-',''),today=()=>new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Tokyo'});
const imageUrl=(g,s)=>'board_guides_api.php?'+new URLSearchParams({action:'image',board:g.board,date:g.date,id:s.image.id,...(preview?{preview:'student'}:{})});
const link=(board,date)=>'board_guides.html?'+new URLSearchParams({board,date,...(preview?{preview:'student'}:{})});
async function api(board,date,payload){await StaffAuth.ready;const c=new AbortController(),t=setTimeout(()=>c.abort(),20000);try{const r=await fetch('board_guides_api.php?'+new URLSearchParams({board,date,...(preview?{preview:'student'}:{})}),{cache:'no-store',signal:c.signal,...(payload?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,board,date})}:{})});const text=await r.text();let j;try{j=JSON.parse(text);}catch{throw Error('案内の応答を確認できませんでした。入力を残して再度お試しください。');}if(!r.ok||!j.ok)throw Error(j.error||'案内を読み込めませんでした。');return j.guide;}catch(e){if(e.name==='AbortError')throw Error('案内の通信に時間がかかっています。再度お試しください。');throw e;}finally{clearTimeout(t);}}
function content(g,s){return `<h2>${esc(s.title)}</h2>${s.image?`<img src="${esc(imageUrl(g,s))}" alt="${esc(s.title)}">`:''}${s.body?`<p>${esc(s.body)}</p>`:''}`;}
function edit(g,saved){
 if(document.querySelector('.bg-editor[open]'))return;const d=document.createElement('dialog');d.className='bg-editor';let dirty=false,busy=false,pendingImages=0,requestId=uid(),draft=g.slides.map(s=>({...s}));
 d.innerHTML=`<form><header><h2>案内・画像を編集（${esc(g.date)}）</h2><button type="button" class="ws-button" data-close>閉じる</button></header><div class="bg-edit-body"><p>表示をONにした案内は、生徒のスマホとモニターに公開します。モニターは「今日の動き → 各案内」の順に繰り返します。</p><label>今日の動きの表示時間（秒）<input type="number" name="mainSeconds" min="5" max="600" required value="${g.mainSeconds}"></label><div class="bg-edit-cards"></div><button type="button" class="ws-button" data-add>＋ 案内を追加</button><p class="bg-preview-note">12件まで。画像はPNG・JPEG・WebP・GIF、1枚1MB・1日合計4MBまで。画像の貼り付けもできます。</p></div><footer><span role="status"></span><button type="submit" class="ws-button primary">公開して保存</button></footer></form>`;
 const $=q=>d.querySelector(q),message=s=>$('[role=status]').textContent=s,changed=()=>{dirty=true;requestId=uid();};
 function close(){if(!busy&&(!dirty||confirm('案内の変更を保存せずに閉じますか？')))d.close();}
 $('[data-close]').onclick=close;d.oncancel=e=>{e.preventDefault();close();};d.onclick=e=>{if(e.target===d)close();};d.onclose=()=>{window.removeEventListener('beforeunload',leave);d.remove();};
 function leave(e){if(dirty||busy){e.preventDefault();e.returnValue='';}}window.addEventListener('beforeunload',leave);
 function row(s){
  const el=document.createElement('section');el.className='bg-edit-card';el.dataset.id=s.id;
  el.innerHTML=`<label class="bg-visible"><input data-visible type="checkbox" ${s.visible?'checked':''}> 表示する</label><label>タイトル<input data-title maxlength="100" value="${esc(s.title)}"></label><label>案内の文章<textarea data-body rows="4" maxlength="4000">${esc(s.body)}</textarea></label><label>この案内の表示時間（秒）<input data-seconds type="number" min="5" max="600" required value="${s.seconds}"></label><label>画像を選択／この枠内で貼り付け<input type="file" data-image accept="image/png,image/jpeg,image/webp,image/gif"></label><img data-preview alt="案内の画像" hidden><button type="button" class="ws-button" data-clear-image hidden>画像を外す</button> <button type="button" class="ws-button" data-up>↑ 上へ</button> <button type="button" class="ws-button" data-down>↓ 下へ</button> <button type="button" class="ws-button" data-remove>この案内を削除</button>`;
  const preview=el.querySelector('[data-preview]'),clear=el.querySelector('[data-clear-image]');function paint(){const src=s.imageData||(s.image?imageUrl(g,s):'');preview.hidden=clear.hidden=!src;if(src)preview.src=src;else preview.removeAttribute('src');}paint();
  async function attach(file){if(!file||busy)return;if(!['image/png','image/jpeg','image/webp','image/gif'].includes(file.type)||file.size>1048576){message('PNG・JPEG・WebP・GIF、1枚1MBまでの画像を選んでください。');return;}pendingImages++;try{const value=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file);});if(!d.open||busy)return;s.imageData=value;s.image=null;paint();changed();message('画像を追加しました。保存すると公開されます。');}catch{message('画像を読み込めませんでした。');}finally{pendingImages--;}}
  el.querySelector('[data-image]').onchange=e=>attach(e.target.files[0]);el.onpaste=e=>{const file=[...(e.clipboardData?.items||[])].find(i=>i.type.startsWith('image/'))?.getAsFile();if(file){e.preventDefault();attach(file);}};el.ondragover=e=>{if(e.dataTransfer?.types.includes('Files'))e.preventDefault();};el.ondrop=e=>{if(e.dataTransfer?.files.length){e.preventDefault();attach(e.dataTransfer.files[0]);}};
  clear.onclick=()=>{s.image=null;s.imageData='';el.querySelector('[data-image]').value='';paint();changed();};
  el.querySelector('[data-remove]').onclick=()=>{if(busy)return;draft=draft.filter(x=>x!==s);el.remove();changed();};
  el.querySelector('[data-up]').onclick=()=>{if(!busy&&el.previousElementSibling){el.before(el.previousElementSibling);changed();}};el.querySelector('[data-down]').onclick=()=>{if(!busy&&el.nextElementSibling){el.nextElementSibling.after(el);changed();}};
  $('.bg-edit-cards').append(el);return el;
 }
 draft.forEach(row);$('[data-add]').onclick=()=>{if(busy)return;if(draft.length>=12){message('案内は12件までです。');return;}const s={id:uid(),title:'',body:'',seconds:10,visible:true,image:null};draft.push(s);row(s).querySelector('[data-title]').focus();changed();};
 d.addEventListener('input',changed);d.addEventListener('change',changed);
 $('form').onsubmit=async e=>{e.preventDefault();if(busy)return;if(pendingImages){message('画像を読み込み中です。読み込み後に保存してください。');return;}const slides=[...d.querySelectorAll('.bg-edit-card')].map(el=>({...draft.find(s=>s.id===el.dataset.id),title:el.querySelector('[data-title]').value,body:el.querySelector('[data-body]').value,visible:el.querySelector('[data-visible]').checked,seconds:Number(el.querySelector('[data-seconds]').value)}));busy=true;d.querySelectorAll('input,textarea,button').forEach(x=>x.disabled=true);message('保存中…');try{const result=await api(g.board,g.date,{mainSeconds:Number($('[name=mainSeconds]').value),slides,version:g.version,requestId});dirty=false;saved(result);d.close();}catch(err){message(err.message);}finally{busy=false;d.querySelectorAll('input,textarea,button').forEach(x=>x.disabled=false);}};
 document.body.append(d);d.showModal();
}
function mount(root,boardId){
 if(root._boardGuides)return;const monitor=new URL(location.href).searchParams.get('mode')==='monitor';let date='',guide=null,busy=false,lastKey='',slides=[],index=-1,paused=false,due=Date.now()+30000,rendered='';
 const tools=root.querySelector('.db-tools'),open=document.createElement('a'),editor=document.createElement('button');open.className=editor.className='ws-button';open.textContent='案内・画像';editor.textContent='案内を編集';editor.type='button';editor.hidden=true;tools.append(open,editor);
 const controls=document.createElement('div');controls.className='bg-controls';controls.hidden=true;controls.innerHTML='<span></span><button type="button" class="ws-button" data-prev>前へ</button><button type="button" class="ws-button" data-pause>一時停止</button><button type="button" class="ws-button" data-next>次へ</button>';
 const stage=document.createElement('section');stage.className='bg-stage';stage.hidden=true;root.querySelector('.db-rows').before(controls,stage);
 const seconds=()=>index<0?(guide?.mainSeconds||30):slides[index]?.seconds||10;
 function paint(){const s=slides[index],key=s?JSON.stringify(s):'';if(key!==rendered){stage.innerHTML=s?content(guide,s):'';rendered=key;}const active=monitor&&!!s;root.classList.toggle('bg-show-guide',active);stage.hidden=!active;controls.hidden=!monitor||!slides.length;controls.querySelector('span').textContent=(index<0?'今日の動き':s?.title||'案内')+' ／ '+(paused?'停止中':Math.max(0,Math.ceil((due-Date.now())/1000))+'秒');}
 function advance(step=1){index+=step;if(index>=slides.length)index=-1;if(index< -1)index=slides.length-1;due=Date.now()+seconds()*1000;paint();}
 function apply(g){guide=g;editor.hidden=!g.canEdit;const next=g.slides.filter(s=>s.visible),key=JSON.stringify([g.mainSeconds,next]);if(key!==lastKey){const current=slides[index]?.id;slides=next;index=current?slides.findIndex(s=>s.id===current):-1;due=Date.now()+seconds()*1000;lastKey=key;rendered='';}paint();}
 async function load(){if(!date||busy)return;const when=date;busy=true;try{const g=await api(boardId,when);if(when===date)apply(g);}catch{open.title='案内を確認できません。クリックして再読み込みしてください。';}finally{busy=false;if(when!==date)load();}}
 root._boardGuides={date(value){if(date!==value){date=value;guide=null;slides=[];index=-1;lastKey='';rendered='';stage.replaceChildren();paint();open.href=link(boardId,date);load();}}};
 editor.onclick=()=>{if(guide?.canEdit)edit(guide,g=>{if(g.date===date)apply(g);});};controls.querySelector('[data-prev]').onclick=()=>advance(-1);controls.querySelector('[data-next]').onclick=()=>advance();controls.querySelector('[data-pause]').onclick=e=>{paused=!paused;e.target.textContent=paused?'再生':'一時停止';if(!paused)due=Date.now()+seconds()*1000;paint();};
 setInterval(()=>{if(document.hidden)return;if(monitor&&slides.length&&!paused&&!document.querySelector('dialog[open]')&&Date.now()>=due)advance();else paint();},500);setInterval(()=>{if(!document.hidden)load();},30000);window.addEventListener('focus',load);
}
async function page(){const root=document.getElementById('boardGuidesPage');if(!root)return;const $=id=>document.getElementById(id),params=new URLSearchParams(location.search),board=params.get('board')==='blue'?'blue':'all',fixed=params.get('date'),date=()=>fixed||today();let guide,busy=false;
 $('bgBack').href=(board==='blue'?'room_board.html':'daily_board.html')+'?'+new URLSearchParams({...fixed?{date:fixed}:{},...preview?{preview:'student'}:{}});
 function paint(g){guide=g;$('bgEdit').hidden=!g.canEdit;$('bgPageStatus').textContent=g.date+(g.updatedAt?' ／ 更新 '+new Date(g.updatedAt).toLocaleString('ja-JP'):' ／ まだ更新されていません');$('bgPageCards').innerHTML=g.slides.filter(s=>s.visible).map(s=>`<article class="bg-card">${content(g,s)}</article>`).join('')||'<p>表示する案内はありません。</p>';}
 async function load(){if(busy)return;busy=true;try{paint(await api(board,date()));}catch(e){$('bgPageStatus').textContent=e.message;}finally{busy=false;}}
 $('bgEdit').onclick=()=>{if(guide?.canEdit)edit(guide,paint);};$('bgReload').onclick=load;setInterval(()=>{if(!document.hidden)load();},30000);window.addEventListener('focus',load);load();
}
window.BoardGuides={mount};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',page);else page();
})();
