(()=>{'use strict';const host=document.getElementById('gridWrap')||document.getElementById('schedule')||document.getElementById('classScheduleList');if(!host)return;const student=location.pathname.endsWith('/student.html'),esc=Workspace.esc;
let data={events:[],schools:[]},seq=0,queued=false,school='',studentName='',loaded=false;
try{school=student?'':sessionStorage.getItem('calendar.school')||'';}catch(e){}
const bar=document.createElement('div');bar.className='ce-calendar-bar';bar.id='calendarEventBar';bar.innerHTML=`${student?'<span id="calendarStudentSchool">所属学校を確認中…</span>':'<label>学校行事 <select id="calendarSchoolFilter"><option value="">全校を表示</option></select></label>'}<a href="notices.html">学校行事・塾のお知らせ一覧</a><button id="calendarEventsReload" type="button">再読み込み</button><span id="calendarEventsMessage" class="ce-calendar-message" role="status"></span>`;host.before(bar);
function decorate(){host.querySelectorAll('[data-calendar-date]').forEach(el=>{const date=el.dataset.calendarDate.replaceAll('/','-');const events=data.events.filter(r=>(r.startDate<=date||(r.kind==='school'&&r.category==='test'&&Math.round((Date.parse(r.startDate+'T00:00:00Z')-Date.parse(date+'T00:00:00Z'))/86400000)<=14))&&date<=r.endDate&&(!school||student||r.kind==='notice'||r.schoolId===school));const preview=[...new Map([...events.filter(r=>r.kind==='school').slice(0,1),...events.filter(r=>r.kind==='notice').slice(0,1),...events].map(r=>[r.id,r])).values()].slice(0,el.dataset.calendarFull==='1'?events.length:2);const label=el.parentElement.querySelector('.whole-day-events-label');if(label){const text='学校行事・お知らせ '+events.length+'件';if(label.textContent!==text)label.textContent=text;}const html=preview.map(r=>`<a class="${r.kind==='notice'?'ce-notice':''}" href="notices.html?id=${r.id}" title="${esc((r.schoolName?r.schoolName+'：':'')+r.title)}">${r.kind==='notice'?'📢 ':esc(r.schoolName)+'：'}${esc(r.title)}${r.category==='test'&&date<r.startDate?'（あと'+Math.round((Date.parse(r.startDate+'T00:00:00Z')-Date.parse(date+'T00:00:00Z'))/86400000)+'日）':''}</a>`).join('')+(events.length>2&&el.dataset.calendarFull!=='1'?`<a href="notices.html?date=${date}${(student?data.studentSchool?.id:school)?'&school='+encodeURIComponent(student?data.studentSchool.id:school):''}">ほか${events.length-2}件</a>`:'');if(el.innerHTML!==html)el.innerHTML=html;});}
function enqueue(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;decorate();});}
async function load(){const call=++seq;loaded=false;if(student){data={events:[],schools:[]};decorate();studentName=window.StudentSchedule?.getStudentName()||'';document.getElementById('calendarStudentSchool').textContent='所属学校を確認中…';}document.getElementById('calendarEventsMessage').textContent='読み込み中…';try{const j=await Workspace.api('calendar_events_api.php'+(student?'?student='+encodeURIComponent(studentName):''));if(seq!==call)return;data=j;loaded=true;if(student)document.getElementById('calendarStudentSchool').textContent=data.studentSchool?'所属学校：'+data.studentSchool.name:studentName?'所属学校が未登録です。塾へ登録を依頼してください。':'生徒名を選ぶと、所属学校の行事を表示します。';else{const el=document.getElementById('calendarSchoolFilter');el.innerHTML='<option value="">全校を表示</option>'+j.schools.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('');if(!j.schools.some(s=>s.id===school))school='';el.value=school;}document.getElementById('calendarEventsMessage').textContent='';decorate();}catch(e){if(seq!==call)return;data={events:[],schools:[]};decorate();document.getElementById('calendarEventsMessage').textContent='行事・お知らせを読み込めません。再読み込みしてください。';if(student)document.getElementById('calendarStudentSchool').textContent='所属学校を確認できません。';}}
document.getElementById('calendarEventsReload').onclick=load;document.getElementById('calendarSchoolFilter')?.addEventListener('change',e=>{school=e.target.value;try{sessionStorage.setItem('calendar.school',school);}catch(err){}decorate();});
new MutationObserver(enqueue).observe(host,{childList:true,subtree:true});document.addEventListener('student-selection-changed',()=>{const next=window.StudentSchedule?.getStudentName()||'';if(next!==studentName)load();else enqueue();});document.addEventListener('history-window-change',enqueue);
host.addEventListener('click',e=>{if(e.target.closest('.ce-day-events a'))e.stopPropagation();});window.addEventListener('pageshow',e=>{if(e.persisted)load();});window.CalendarView={reload:load,get loaded(){return loaded;}};StaffAuth.ready.then(load);
})();
