<?php
require_once __DIR__.'/staff_security.php';header('Cache-Control: private, no-store');header('Vary: Cookie');
$viewer=staffCurrent();if(!$viewer){header('Location: staff_login.html?next=codex_memos.php',true,303);exit;}if($viewer['mustChange']){header('Location: staff_account.html',true,303);exit;}staffRequire(true);header('Content-Type: text/html; charset=utf-8');
?>
<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>CODEXメモ</title><link rel="stylesheet" href="workspace-ui.css?v=20260912-r24"><link rel="stylesheet" href="codex-memos.css?v=20260916-r54-ready"><script src="staff-auth.js?v=20260917-r56-ready" data-staff="required"></script><script defer src="workspace-ui.js?v=20260916-r54-ready"></script></head><body><main class="workspace-page cm-page" id="codexMemoPage">
<header class="cm-page-head"><div><h1>CODEXメモ</h1><small>更新版 r56</small><p>気づいたことを集めて、修正を依頼するメモです。管理者だけが閲覧できます。</p></div><button type="button" class="ws-button primary" data-cm-new>＋ メモを書く</button></header>
<section class="ws-panel cm-help"><strong>記録 → 回答・対応結果を確認 → 続きを相談</strong><p>質問は新規メモの種類で「質問」を選んでください。各メモの「回答・対応結果」に返答が残ります。「Codexで続きを相談（履歴をコピー）」で相談コード・元の質問・追記・回答をまとめてコピーし、Codexの会話に貼り付けて追加の質問を書いてください。</p><p>各ページの「CODEXメモ」で「新規メモ」か「既存メモに追記」を選べます。同じ内容の検証結果は、各メモの「このメモに追記」から文章・画像を追加してください。下のボタンでコピーした文章をCodexへ貼り付けてください。画像も渡す場合はZIPを添付してください。</p><p>「元のページを開く」で確認し、直っていたら「修正を確認・対応完了」を押すと一覧から隠れます。コピーやページを開くだけでは対応完了になりません。元のページのCODEXメモ欄にも現在の状態を表示し、「対応完了」「追記」で結果を記録できます。いつもの「✎ CODEXメモ」アイコンは、新規メモで開きます。追記は記入者・日時とともに同じメモに残り、一括コピー・ZIPにも含まれます。対応完了への追記は未対応に戻します。</p></section>
<div class="cm-list-tools"><label>検索<input type="search" id="cmSearch" placeholder="相談コード・メモ・回答で検索"></label><label>状態<select id="cmStatusFilter"><option value="active">未完了すべて</option><option value="open" selected>未対応</option><option value="reviewing">検証中</option><option value="hold">保留</option><option value="returned">差し戻し</option><option value="done">対応完了</option><option value="all">すべて</option></select></label><label>並び順<select id="cmSort"><option value="desc">更新日時：新しい順（降順）</option><option value="asc" selected>更新日時：古い順（昇順）</option></select></label><input type="checkbox" id="cmShowDone" hidden><button type="button" class="ws-button" id="cmReload">再読み込み</button></div>
<div class="cm-export-tools"><button type="button" class="ws-button primary" id="cmCopy">表示中の未完了を一括コピー</button><button type="button" class="ws-button" id="cmZip">画像付きZIP</button><span id="cmCount"></span></div><p id="cmListMessage" class="ws-message" role="status"></p><div id="cmList"></div>
</main></body></html>
