(()=>{'use strict';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=v=>v?new Date(v).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'}):'—';
let jobs=[],memos=[],labels={},busy=false,loading=false,detailId='',last='';
async function api(path,payload){const r=await fetch(path,payload?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}:{cache:'no-store'});let j;try{j=await r.json();}catch{throw Error('応答を読み取れません。再読み込みしてください。');}if(!r.ok||!j.ok)throw Error(j.error||'処理できませんでした。');return j;}
function safePage(path){const u=new URL(path||'codex_memos.php',location.origin);return u.origin===location.origin?u.href:'codex_memos.php';}
function rows(){const mapped=new Set(jobs.map(j=>j.memoId));return [...jobs,...memos.filter(m=>!mapped.has(m.id)&&!m.doneAt).map(m=>({id:'memo-'+m.id,memoId:m.id,referenceCode:m.referenceCode,pageTitle:m.pageTitle,pagePath:m.pagePath,requestText:m.text,status:'unprocessed',createdAt:m.createdAt,createdBy:m.createdBy,level:null}))];}
function filtered(){const q=$('cqSearch').value.toLocaleLowerCase().trim(),status=$('cqStatus').value,level=$('cqLevel').value;return rows().filter(j=>(status==='all'||(status==='active'?!j.completedAt:j.status===status))&&(!level||String(j.level)===level)&&(!q||[j.referenceCode,j.pageTitle,j.requestText,j.answer].join(' ').toLocaleLowerCase().includes(q))).sort((a,b)=>($('cqSort').value==='asc'?1:-1)*(a.createdAt.localeCompare(b.createdAt)||a.id.localeCompare(b.id)));}
function actionButtons(j){const active=['queued','running','fixed','testing'].includes(j.status);return `${j.status==='unprocessed'?'<button class="ws-button primary" data-action="enqueue">Codexへ送信</button>':''}${active?'<button class="ws-button" data-action="stop">処理停止</button><button class="ws-button" data-action="hold">保留</button>':''}${['hold','failed','review','tested'].includes(j.status)?'<button class="ws-button" data-action="retry">再実行</button>':''}${!active&&j.status!=='unprocessed'&&!j.completedAt?'<button class="ws-button" data-action="complete">結果を確認済みにする</button>':''}<button class="ws-button" data-detail>詳細を見る</button><a class="ws-button" href="codex_memos.php?memo=${encodeURIComponent(j.memoId)}">元のメモ</a>`;}
function render(){const list=filtered();$('cqCount').textContent=`${list.length}件表示`;$('cqList').innerHTML=list.map(j=>`<article class="cq-card" data-id="${esc(j.id)}"><div class="cq-card-head"><div><h2>${esc(j.pageTitle)}</h2><span class="cq-code">${esc(j.referenceCode)}</span></div><div class="cq-badges"><span class="cq-badge">${j.level?'LEVEL '+j.level:'レベル判定前'}</span><span class="cq-badge" data-status="${esc(j.status)}">${esc(labels[j.status]||j.status)}</span>${j.completedAt?'<span class="cq-badge">確認済み</span>':''}</div></div><p class="cq-request">${esc(j.requestText)||'画像の依頼'}</p><dl><div><dt>登録</dt><dd>${date(j.createdAt)}</dd></div><div><dt>開始</dt><dd>${date(j.startedAt)}</dd></div><div><dt>終了</dt><dd>${date(j.finishedAt)}</dd></div></dl>${j.answer?'<div class="cq-answer">'+esc(j.answer)+'</div>':''}${j.error?'<p class="cq-fail">'+esc(j.error)+'</p>':''}<div class="cq-actions">${actionButtons(j)}</div><p class="cq-note">本番反映：未実施 · commit：なし</p></article>`).join('')||'<p class="cq-empty">該当するメモはありません。</p>';}
function detail(j){detailId=j.id;const m=memos.find(m=>m.id===j.memoId),images=[...(m?.images||[]),...(m?.updates||[]).flatMap(u=>u.images||[])];$('cqDetailBody').innerHTML=`<p class="cq-code">${esc(j.referenceCode)}</p><h3>${esc(j.pageTitle)}</h3><pre>${esc(j.requestText)||'画像の依頼'}</pre><a href="${esc(safePage(j.pagePath))}" target="_blank" rel="noopener">対象ページを開く</a>${m?.updates?.length?'<h3>追記</h3>'+m.updates.map(u=>'<pre>'+esc(u.text)+'</pre>').join(''):''}<div class="cq-images">${images.map(i=>`<a href="codex_memos_api.php?action=image&memo=${encodeURIComponent(j.memoId)}&id=${encodeURIComponent(i.id)}" target="_blank" rel="noopener"><img src="codex_memos_api.php?action=image&memo=${encodeURIComponent(j.memoId)}&id=${encodeURIComponent(i.id)}" alt="依頼の添付画像"></a>`).join('')}</div><h3>判定・処理結果</h3><p>${esc(labels[j.status]||j.status)} / ${j.level?'LEVEL '+j.level:'判定前'}</p><p>${esc(j.levelReason)}</p><pre>${esc(j.answer)||'回答はまだありません。'}</pre>${j.error?'<p class="cq-fail">'+esc(j.error)+'</p>':''}<h3>変更ファイル</h3><ul>${(j.changedFiles||[]).map(p=>'<li><code>'+esc(p)+'</code></li>').join('')||'<li>なし</li>'}</ul><h3>テスト</h3><ul>${(j.tests||[]).map(t=>`<li class="${t.passed?'cq-pass':'cq-fail'}">${t.passed?'✓':'×'} ${esc(t.name)}${t.detail?'<br><small>'+esc(t.detail)+'</small>':''}</li>`).join('')||'<li>未実施</li>'}</ul><h3>修正候補</h3><p>候補ID：<code>${esc(j.candidateId)||'—'}</code></p><p>元のcommit：<code>${esc(j.baseCommit)||'—'}</code></p><p>パッチSHA256：<code>${esc(j.patchSha256)||'—'}</code></p><p>commit SHA：なし / Actions Run：なし / 本番反映：未実施</p><h3>状態の履歴</h3><ul>${(j.history||[]).map(h=>'<li>'+date(h.at)+' · '+esc(labels[h.status]||h.status)+' · '+esc(h.by)+'<br>'+esc(h.message)+'</li>').join('')||'<li>まだ送信していません。</li>'}</ul><div class="cq-phase-actions"><button class="ws-button" disabled title="第1段階では利用できません">承認して本番反映（準備中）</button><p class="cq-note">第1段階では修正候補を確認して終了します。確認済みにしても元の修正メモは自動で対応完了になりません。</p></div>`;if(!$('cqDetail').open)$('cqDetail').showModal();}
async function load(force=false){if(loading||busy)return;loading=true;try{const [q,m]=await Promise.all([api('codex_queue_api.php'),api('codex_memos_api.php?includeDone=1')]);jobs=q.items;memos=m.items;if(!Object.keys(labels).length){labels=q.labels;$('cqStatus').insertAdjacentHTML('beforeend',Object.entries(labels).map(([v,t])=>`<option value="${esc(v)}">${esc(t)}</option>`).join(''));}const fingerprint=JSON.stringify([jobs,memos]);if(force||fingerprint!==last){last=fingerprint;render();if($('cqDetail').open){const j=rows().find(x=>x.id===detailId);if(j)detail(j);}}$('cqRefresh').textContent='確認 '+date(new Date().toISOString())+' · 5秒ごと';}catch(e){$('cqMessage').textContent=e.message;}finally{loading=false;}}
$('cqFilters').onsubmit=e=>e.preventDefault();for(const id of ['cqSearch','cqStatus','cqLevel','cqSort'])$(id).addEventListener(id==='cqSearch'?'input':'change',render);$('cqReload').onclick=()=>load(true);$('cqDetail').querySelector('[data-close]').onclick=()=>$('cqDetail').close();$('cqDetail').onclick=e=>{if(e.target===$('cqDetail')){$('cqDetail').close();}};
$('cqList').onclick=async e=>{const card=e.target.closest('[data-id]'),button=e.target.closest('button');if(!card||!button||busy)return;const job=rows().find(j=>j.id===card.dataset.id);if(!job)return;if(button.hasAttribute('data-detail'))return detail(job);const action=button.dataset.action;if(!action)return;if((action==='enqueue'||action==='retry')&&!confirm('このメモの内容・添付画像をCodexへ渡して改修・テストします。本番反映はしません。送信しますか？'))return;busy=true;button.disabled=true;try{let payload={action,id:job.id,version:job.version};if(action==='enqueue'||action==='retry'){const m=(await api('codex_memos_api.php?id='+encodeURIComponent(job.memoId))).items[0];payload={action,memoId:job.memoId,memoVersion:m.version};}const result=await api('codex_queue_api.php',payload);$('cqMessage').textContent=result.duplicate?'このメモはすでに送信済みです。状態を確認してください。':'操作を受け付けました。';}catch(err){$('cqMessage').textContent=err.message;}finally{busy=false;await load(true);}};
StaffAuth.ready.then(()=>{load(true);setInterval(()=>{if(!document.hidden&&!$('cqDetail').open)load();},5000);window.addEventListener('focus',()=>load());});
})();
