(()=>{'use strict';
if(window.CodexMemos)return;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>[...crypto.getRandomValues(new Uint8Array(16))].map(x=>x.toString(16).padStart(2,'0')).join('');
const date=v=>v?new Date(v).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo',year:'numeric',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}):'';
const imageUrl=(memo,i)=>'codex_memos_api.php?action=image&memo='+encodeURIComponent(memo.id)+'&id='+encodeURIComponent(i.id);
async function request(payload,query=''){
 let response,raw;try{response=await fetch('codex_memos_api.php'+query,payload?{method:'POST',...(payload instanceof FormData?{body:payload}:{headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)})}:{cache:'no-store'});raw=await response.text();}catch{throw Error('通信できませんでした。入力内容を残しています。再度お試しください。');}
 let j;try{j=JSON.parse(raw);}catch{throw Error('正常な応答を読み取れませんでした。一覧で保存状況を確認してから再度お試しください。（CM_HTTP_'+response.status+'）');}if(!response.ok||!j.ok){const error=Error(j.error||'メモを処理できませんでした。');error.status=response.status;throw error;}return j;
}
function pageLink(item,review=false){const u=new URL(item.pagePath,location.origin);if(u.origin!==location.origin)return '#';if(review)u.searchParams.set('cmMemo',item.id);return u.href;}
function changed(){window.dispatchEvent(new Event('codex-memo-changed'));try{localStorage.setItem('codex-memo-change',uid());}catch{}}
function source(){const u=new URL(location.href);u.searchParams.delete('cmMemo');const dialogs=[...document.querySelectorAll('dialog[open]:not([data-cm-dialog]),#modal:not(.hidden)')];const d=dialogs.at(-1);return {pageTitle:document.title,pagePath:u.pathname+u.search+u.hash,context:d?(d.querySelector('h1,h2,h3,.modal-title')?.textContent||d.getAttribute('aria-label')||'詳細画面').trim().slice(0,400):''};}
function makeDialog(label,html){const d=document.createElement('dialog');d.className='cm-dialog';d.dataset.cmDialog='';d.setAttribute('aria-label',label);d.innerHTML=html;document.body.append(d);return d;}
function showImage(item,i){const d=makeDialog('メモの画像',`<header class="cm-dialog-head"><h2>メモの画像</h2><button type="button" class="ws-button" data-close>閉じる</button></header><div class="cm-image-view"><img src="${esc(imageUrl(item,i))}" alt="メモに添付した画像"><a class="ws-button" href="${esc(imageUrl(item,i))}" target="_blank" rel="noopener">画像だけを開く</a></div>`);d.querySelector('[data-close]').onclick=()=>d.close();d.onclose=()=>d.remove();d.showModal();}
function compose(options={}){
 if(document.querySelector('[data-cm-compose]'))return;
 const src=source(),preferred=options.item?.id||'';
 const d=makeDialog('CODEXメモを書く',`<form><header class="cm-dialog-head"><h2>CODEXメモ</h2><a href="codex_memos.php" target="_blank" rel="noopener">一覧を開く</a><button type="button" class="ws-button" data-close>閉じる</button></header><div class="cm-dialog-body"><fieldset class="cm-write-mode"><legend>書き込み方法</legend><label><input type="radio" name="mode" value="create" ${preferred?'':'checked'}>新規メモ</label><label><input type="radio" name="mode" value="append" ${preferred?'checked':''}>既存メモに追記</label></fieldset><div class="cm-target-box" hidden><label class="cm-field">追記先を探す<input type="search" name="targetSearch" placeholder="メモ・ページ名で検索"></label><label class="cm-field">追記するメモ<select name="target" size="5"><option value="">読み込み中…</option></select></label><button type="button" class="ws-button" data-target-reload>追記先を再読み込み</button><p class="cm-target-status" role="status"></p><div class="cm-target-preview"></div></div><label class="cm-field cm-kind">新規メモの種類<select name="kind"><option value="request">修正依頼</option><option value="question">質問</option></select></label><p class="cm-source"><strong>${esc(src.pageTitle)}</strong>${src.context?'<br>'+esc(src.context):''}<br><small>書き込んだページのURL・記入者・日時を記録します。</small></p><label class="cm-field"><span data-text-label>メモ</span><textarea name="text" rows="5" maxlength="8000" placeholder="気づいたこと、検証結果、追加の依頼を入力"></textarea></label><div class="cm-paste" tabindex="0"><strong>画像を貼り付け（Ctrl＋V）</strong><span>ここへ画像をドラッグすることもできます。</span><label class="ws-button cm-file-label">画像を選ぶ<input type="file" accept="image/png,image/jpeg,image/webp,image/gif" multiple></label><small>今回の書き込みに4枚まで・1枚2MB／合計6MB</small></div><div class="cm-previews"></div><p class="cm-help-text">追記は同じメモにまとまり、コピー・ZIPにも含まれます。対応完了のメモに追記すると、未対応に戻します。</p></div><footer class="cm-dialog-foot"><span class="cm-save-status" role="status"></span><button type="submit" class="ws-button primary">メモを保存</button></footer></form>`);
 d.dataset.cmCompose='';let files=[],busy=false,dirty=false,requestId=uid(),targets=[],selectedId=preferred,targetsReady=false,targetTicket=0;
 const message=d.querySelector('.cm-save-status'),form=d.querySelector('form'),targetSelect=form.elements.target;
 const isAppend=()=>form.elements.mode.value==='append',target=()=>targets.find(r=>r.id===selectedId);
 function touch(){dirty=true;requestId=uid();}
 function preview(){const r=target();d.querySelector('.cm-target-preview').innerHTML=r?`<strong>${esc(r.pageTitle)}</strong><p>${esc(r.text)||'（画像のメモ）'}</p>${(r.updates||[]).length?'<p>最新の追記：'+esc(r.updates.at(-1).text||'画像')+'</p>':''}<small>${r.doneAt?'対応完了 → 保存すると未対応に戻します':statusLabel(r)} · ${date(r.updatedAt||r.createdAt)}</small>`:'';}
 function drawTargets(){const q=form.elements.targetSearch.value.trim().toLocaleLowerCase();const rows=targets.filter(r=>r.id===selectedId||!q||[r.text,r.pageTitle,r.id,...(r.updates||[]).map(u=>u.text)].join(' ').toLocaleLowerCase().includes(q));targetSelect.innerHTML='<option value="">追記先を選択してください</option>'+rows.map(r=>`<option value="${esc(r.id)}">${r.doneAt?'[対応完了] ':''}${esc(r.pageTitle)}｜${esc((r.text||'画像のメモ').replace(/\s+/g,' ').slice(0,100))}（追記${(r.updates||[]).length}件）</option>`).join('');targetSelect.value=selectedId;preview();}
 function mode(){d.querySelector('.cm-target-box').hidden=!isAppend();d.querySelector('.cm-kind').hidden=isAppend();d.querySelector('[data-text-label]').textContent=isAppend()?'追記内容':'メモ';d.querySelector('[type=submit]').textContent=isAppend()?'このメモに追記を保存':'新規メモを保存';}
 async function loadTargets(){const seq=++targetTicket,notice=d.querySelector('.cm-target-status');targetsReady=false;notice.textContent='メモを読み込み中…';try{const j=await request(null,'?includeDone=1');if(seq!==targetTicket||!d.isConnected)return;targets=j.items;targetsReady=true;targets.sort((a,b)=>Number(b.pagePath.split('?')[0]===src.pagePath.split('?')[0])-Number(a.pagePath.split('?')[0]===src.pagePath.split('?')[0]));drawTargets();notice.textContent=selectedId&&!target()?'追記先が見つかりません。別のメモを選んでください。':targets.length?'追記先と内容を確認してください。':'メモはまだありません。「新規メモ」で登録してください。';}catch(e){if(seq===targetTicket)notice.textContent=e.message;}}
 function paint(){d.querySelector('.cm-previews').innerHTML=files.map((f,i)=>`<div class="cm-preview"><img src="${esc(f.url)}" alt="添付画像 ${i+1}"><button type="button" class="ws-button" data-remove="${i}">画像${i+1}を外す</button></div>`).join('');}
 function add(incoming){if(busy)return;const next=[...incoming];if(!next.length)return;if(files.length+next.length>4){message.textContent='今回の書き込みには画像4枚までです。';return;}if(next.some(f=>!['image/png','image/jpeg','image/webp','image/gif'].includes(f.type)||f.size>2*1024*1024||!f.size)){message.textContent='PNG・JPEG・WebP・GIFの画像を選んでください。1枚2MBまでです。';return;}if(files.reduce((n,x)=>n+x.file.size,0)+next.reduce((n,x)=>n+x.size,0)>6*1024*1024){message.textContent='今回の画像の合計は6MBまでです。';return;}files.push(...next.map(file=>({file,url:URL.createObjectURL(file)})));touch();message.textContent='';paint();}
 const picker=d.querySelector('input[type=file]');picker.onchange=()=>{add(picker.files);picker.value='';};
 d.addEventListener('paste',e=>{const imgs=[...(e.clipboardData?.items||[])].filter(x=>x.kind==='file'&&x.type.startsWith('image/')).map(x=>x.getAsFile()).filter(Boolean);if(imgs.length){e.preventDefault();add(imgs);}});
 const drop=d.querySelector('.cm-paste');drop.ondragover=e=>e.preventDefault();drop.ondrop=e=>{e.preventDefault();add(e.dataTransfer.files);};
 form.elements.kind.onchange=touch;form.elements.text.oninput=touch;form.querySelectorAll('[name=mode]').forEach(el=>el.onchange=()=>{touch();mode();});form.elements.targetSearch.oninput=drawTargets;targetSelect.onchange=()=>{selectedId=targetSelect.value;touch();preview();};d.querySelector('[data-target-reload]').onclick=loadTargets;
 d.querySelector('.cm-previews').onclick=e=>{const b=e.target.closest('[data-remove]');if(!b||busy)return;URL.revokeObjectURL(files[+b.dataset.remove].url);files.splice(+b.dataset.remove,1);touch();paint();};
 function close(){if(!busy&&(!dirty||confirm('保存せずにCODEXメモを閉じますか？')))d.close();}
 d.querySelector('[data-close]').onclick=close;d.oncancel=e=>{e.preventDefault();close();};d.onclose=()=>{files.forEach(f=>URL.revokeObjectURL(f.url));d.remove();};
 const before=e=>{if(dirty&&d.open){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',before);d.addEventListener('close',()=>window.removeEventListener('beforeunload',before));
 form.onsubmit=async e=>{e.preventDefault();if(busy)return;const append=isAppend(),r=target(),text=form.elements.text.value.trim();if(append&&(!targetsReady||!r)){message.textContent='追記先のメモを読み込み、選択してください。';return;}if(!text&&!files.length){message.textContent='メモを入力するか画像を添付してください。';return;}const data=new FormData();Object.entries({...src,action:append?'append':'create',kind:form.elements.kind.value,text,requestId,...(append?{id:r.id,version:r.version}:{})}).forEach(([k,v])=>data.set(k,v));files.forEach(f=>data.append('images[]',f.file,f.file.name||'pasted-image.png'));busy=true;d.querySelectorAll('input,textarea,select,button').forEach(x=>x.disabled=true);message.textContent='保存中…';
  try{await request(data);dirty=false;changed();d.close();toast(append?'同じメモに追記しました。':'新規のCODEXメモを保存しました。');}catch(err){message.textContent=err.message;}finally{busy=false;d.querySelectorAll('input,textarea,select,button').forEach(x=>x.disabled=false);}
 };mode();d.showModal();form.querySelector('[name=mode]:checked').focus();loadTargets();
}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-code-copy]');if(!b)return;try{await navigator.clipboard.writeText(b.dataset.codeCopy);toast('相談コードをコピーしました。');}catch{const d=makeDialog('相談コードをコピー','<div class="cm-dialog-body"><p>選択したコードをコピーしてください。</p><input readonly aria-label="相談コード"><button type="button">閉じる</button></div>');d.querySelector('input').value=b.dataset.codeCopy;d.querySelector('button').onclick=()=>d.close();d.onclose=()=>d.remove();d.showModal();d.querySelector('input').select();}});
function toast(text){let p=document.getElementById('cmToast');if(!p){p=document.createElement('p');p.id='cmToast';p.setAttribute('role','status');document.body.append(p);}p.textContent=text;p.hidden=false;setTimeout(()=>p.hidden=true,4500);}
function historyText(r){let s='相談コード：'+(r.referenceCode||'CM-'+r.id)+'\n種別：'+(r.kind==='question'?'質問':'修正依頼')+'\n対応状況：'+(r.doneAt?'対応完了 '+r.doneBy+' '+date(r.doneAt):statusLabel(r))+'\n';for(const a of r.responses||[])s+='\n【'+a.kind+' / '+a.release+'】'+a.by+' / '+a.at+'\n'+a.text+'\n';for(const h of r.history||[])s+='操作履歴：'+h.action+(h.status?' ('+h.status+')':'')+' / '+h.by+' / '+date(h.at)+'\n';return s+'\n追加の質問・依頼：\n\n';}
function memoStatus(r){return r.doneAt?'done':['reviewing','hold','returned'].includes(r.status)?r.status:'open';}
function statusLabel(r){return {open:'未対応',reviewing:'検証中',hold:'保留',returned:'差し戻し',done:'対応完了'}[memoStatus(r)];}
function statusSelect(r){return '<label class="cm-status-control">状態 <select data-memo-status aria-label="このメモの状態">'+Object.entries({open:'未対応',reviewing:'検証中',hold:'保留',returned:'差し戻し',done:'対応完了'}).map(([v,t])=>'<option value="'+v+'" '+(memoStatus(r)===v?'selected':'')+'>'+t+'</option>').join('')+'</select></label>';}
function resultState(r){if(r.doneAt)return 'done';if(['reviewing','hold','returned'].includes(r.status))return r.status;const last=(r.responses||[]).at(-1);if(!last)return 'pending';const follow=(r.updates||[]).at(-1),answeredAt=String(last.at||'');return follow&&Date.parse(follow.createdAt)>Date.parse(answeredAt.length===10?answeredAt+'T00:00:00+09:00':answeredAt)?'followup':'answered';}
function responseHtml(r){const answers=r.responses||[];return `<section class="cm-response"><h3>回答・対応結果 ${answers.length?answers.length+'件':''}</h3><p class="cm-reference">相談コード <button type="button" class="cm-code-copy" data-code-copy="${esc(r.referenceCode||'CM-'+r.id)}" title="相談コードをコピー"><code>${esc(r.referenceCode||'CM-'+r.id)}</code> ⧉</button></p>${answers.length?answers.map(a=>`<article><p class="cm-meta">${esc(a.kind)} · ${esc(a.release)} · ${esc(a.by)} · ${esc(a.at)}</p><p class="cm-text">${esc(a.text)}</p></article>`).join(''):'<p>回答・対応結果はまだ登録されていません。</p>'}<p class="cm-meta">「履歴をコピー」でこのメモの質問・追記・回答をCodexに渡せます。コードだけでは別の会話の履歴を自動取得できません。</p><div class="cm-card-actions"><button class="ws-button" type="button" data-history-copy>Codexで続きを相談（履歴をコピー）</button><button class="ws-button" type="button" data-history-zip>履歴の画像付きZIP</button></div></section>`;}
function copyText(items){let s='時間割システム CODEXメモ（修正依頼）\n以下のメモの質問・修正依頼と回答履歴を確認し、追加の質問や依頼に対応してください。運用データは保持してください。回答・修正結果は、このメモの結果欄にも残してください。\n画像がある場合は「画像付きZIP」も添付します。\n\n';for(const r of items){s+=`【メモ ${r.id}】\nページ：${r.pageTitle}\nURL：${pageLink(r)}\n${r.context?'画面内の場所：'+r.context+'\n':''}記入：${r.createdBy} ／ ${date(r.createdAt)}\n\n${r.text}\n`;for(const i of r.images)s+=`画像：images/${r.id}/${i.id}.${i.ext}\n`;s+='\n';for(const [index,u] of (r.updates||[]).entries()){s+=`【追記 ${index+1}】\n記入：${u.createdBy} ／ ${date(u.createdAt)}\nページ：${u.pageTitle}\nURL：${pageLink(u)}\n${u.context?'画面内の場所：'+u.context+'\n':''}\n${u.text}\n`;for(const i of u.images)s+=`画像：images/${r.id}/${i.id}.${i.ext}\n`;s+='\n';}s+=historyText(r);}return s;}
async function copy(items,message){const text=copyText(items);try{await navigator.clipboard.writeText(text);message.textContent=items.length+'件をコピーしました。Codexへ貼り付けてください。';}catch{const d=makeDialog('指示をコピー',`<header class="cm-dialog-head"><h2>指示をコピー</h2><button type="button" class="ws-button">閉じる</button></header><div class="cm-dialog-body"><p>全文を選択しています。Ctrl＋C、または端末のコピー操作でコピーしてください。</p><textarea class="cm-copy-text" rows="14" readonly>${esc(text)}</textarea></div>`);d.querySelector('button').onclick=()=>d.close();d.onclose=()=>d.remove();d.showModal();const t=d.querySelector('textarea');t.focus();t.select();}}
async function download(items,message,history=false){let r;try{r=await fetch('codex_memos_api.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:history?'history_export':'export',ids:items.map(x=>x.id)})});}catch{throw Error('ZIPを取得できませんでした。通信を確認してください。');}if(!r.ok||!r.headers.get('Content-Type')?.includes('application/zip')){let j;try{j=await r.json();}catch{}throw Error(j?.error||'ZIPを作成できませんでした。');}const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='CODEXメモ_'+new Date().toISOString().slice(0,10)+'.zip';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);message.textContent='画像付きZIPをダウンロードしました。Codexへ添付してください。';}
async function mark(item,done){const j=await request({action:'done',id:item.id,version:item.version,done});changed();return j.item;}
function updatesHtml(r){return (r.updates||[]).length?`<section class="cm-updates"><h3>追記 ${(r.updates||[]).length}件</h3>${r.updates.map((u,n)=>`<article class="cm-update"><p class="cm-meta">追記${n+1} · ${esc(u.createdBy)} · ${date(u.createdAt)}</p><p class="cm-text">${esc(u.text)||'（画像のみの追記）'}</p><div class="cm-card-images">${u.images.map((i,index)=>`<button type="button" class="cm-thumbnail" data-update="${esc(u.id)}" data-image="${index}" aria-label="追記${n+1}の画像${index+1}を拡大"><img src="${esc(imageUrl(r,i))}" loading="lazy" alt="追記${n+1}の画像${index+1}"></button>`).join('')}</div><a class="cm-meta" href="${esc(pageLink(u))}" target="_blank" rel="noopener">記入したページ：${esc(u.pageTitle)}</a></article>`).join('')}</section>`:'';}
function listPage(){
 const root=document.getElementById('codexMemoPage');if(!root)return;const $=id=>document.getElementById(id);let items=[],ticket=0,loaded=false,working=false;
 function filtered(){const q=$('cmSearch').value.trim().toLocaleLowerCase();return items.filter(x=>($('cmStatusFilter').value==='all'||($('cmStatusFilter').value==='active'?!x.doneAt:memoStatus(x)===$('cmStatusFilter').value))&&(!q||[x.text,x.pageTitle,x.context,x.id,x.referenceCode,...(x.responses||[]).map(a=>a.text),...(x.updates||[]).map(u=>u.text+' '+u.context+' '+u.pageTitle)].join(' ').toLocaleLowerCase().includes(q))).sort((a,b)=>($('cmSort').value==='asc'?1:-1)*((a.updatedAt||a.createdAt).localeCompare(b.updatedAt||b.createdAt)||a.id.localeCompare(b.id)));}
 function render(){const rows=filtered(),pending=rows.filter(x=>!x.doneAt);$('cmCount').textContent=`${rows.length}件表示 ／ コピー対象 ${pending.length}件`;$('cmCopy').disabled=$('cmZip').disabled=!loaded||working||!pending.length;$('cmList').innerHTML=rows.map(r=>`<article class="cm-card ${r.doneAt?'cm-done':'cm-'+resultState(r)}" data-cm-id="${esc(r.id)}"><div class="cm-card-head"><h2>${esc(r.pageTitle)}</h2><span class="cm-state">${['done','reviewing','hold','returned'].includes(resultState(r))?statusLabel(r):resultState(r)==='answered'?'対応結果あり・検証待ち':resultState(r)==='followup'?'追記への対応待ち':r.kind==='question'?'質問・回答待ち':'未対応'}</span></div><p class="cm-meta">${esc(r.createdBy)} · ${date(r.createdAt)} · <span>${esc(r.id)}</span></p>${r.context?'<p class="cm-meta">'+esc(r.context)+'</p>':''}<p class="cm-text">${esc(r.text)||'（画像のみのメモ）'}</p><div class="cm-card-images">${r.images.map((i,n)=>`<button type="button" class="cm-thumbnail" data-image="${n}" aria-label="添付画像${n+1}を拡大"><img src="${esc(imageUrl(r,i))}" loading="lazy" alt="添付画像${n+1}"></button>`).join('')}</div>${updatesHtml(r)}${responseHtml(r)}<p class="cm-page-url">${esc(pageLink(r))}</p>${r.doneAt?'<p class="cm-meta">修正確認：'+esc(r.doneBy)+' · '+date(r.doneAt)+'</p>':''}<div class="cm-card-actions">${statusSelect(r)}<a class="ws-button" href="${esc(pageLink(r,true))}" target="_blank" rel="noopener">元のページを開く</a><button type="button" class="ws-button" data-append>このメモに追記</button><button type="button" class="ws-button" data-copy>このメモをコピー</button><button type="button" class="ws-button ${r.doneAt?'':'primary'}" data-done>${r.doneAt?'未対応に戻す':'修正を確認・対応完了'}</button></div></article>`).join('')||'<p class="cm-empty">'+(loaded?'該当するメモはありません。':'読み込み中…')+'</p>';}
 async function load(){const n=++ticket;try{const j=await request(null,'?includeDone=1');if(n!==ticket)return;items=j.items;loaded=true;$('cmListMessage').textContent='';render();}catch(e){if(n!==ticket)return;loaded=false;if(e.status===401||e.status===403)items=[];$('cmListMessage').textContent=e.message;render();}}
 const requested=new URL(location.href).searchParams.get('memo');if(/^[a-f0-9]{24}$/.test(requested||'')){$('cmSearch').value=requested;$('cmShowDone').checked=true;$('cmStatusFilter').value='all';}
 $('cmStatusFilter').onchange=render;$('cmSort').onchange=render;$('cmSearch').oninput=render;$('cmShowDone').onchange=render;$('cmReload').onclick=load;root.querySelector('[data-cm-new]').onclick=()=>compose();
 for(const [id,fn] of [['cmCopy',copy],['cmZip',download]])$(id).onclick=async()=>{const rows=filtered().filter(r=>!r.doneAt);if(!rows.length||working)return;working=true;render();try{await fn(rows,$('cmListMessage'));}catch(e){$('cmListMessage').textContent=e.message;}finally{working=false;render();}};
 $('cmList').onchange=async e=>{if(!e.target.matches('[data-memo-status]'))return;const r=items.find(x=>x.id===e.target.closest('[data-cm-id]').dataset.cmId);e.target.disabled=true;try{await request({action:'status',id:r.id,version:r.version,status:e.target.value});changed();await load();}catch(err){$('cmListMessage').textContent=err.message;e.target.value=memoStatus(r);e.target.disabled=false;}};
 $('cmList').onclick=async e=>{const card=e.target.closest('[data-cm-id]');if(!card)return;const r=items.find(x=>x.id===card.dataset.cmId),button=e.target.closest('button');if(!r||!button)return;if(button.hasAttribute('data-append')){compose({item:r});return;}if(button.hasAttribute('data-image')){const imgs=button.dataset.update?(r.updates||[]).find(u=>u.id===button.dataset.update)?.images:r.images;const img=imgs?.[+button.dataset.image];if(img)showImage(r,img);return;}if(button.hasAttribute('data-history-copy')){await copy([r],$('cmListMessage'));return;}if(button.hasAttribute('data-history-zip')){button.disabled=true;try{await download([r],$('cmListMessage'),true);}catch(err){$('cmListMessage').textContent=err.message;}finally{button.disabled=false;}return;}if(button.hasAttribute('data-copy')){await copy([r],$('cmListMessage'));return;}if(button.hasAttribute('data-done')){button.disabled=true;try{await mark(r,!r.doneAt);await load();}catch(err){$('cmListMessage').textContent=err.message;button.disabled=false;}}};
 window.addEventListener('focus',load);window.addEventListener('codex-memo-changed',load);window.addEventListener('storage',e=>{if(e.key==='codex-memo-change')load();});load();
}
let reviewTicket=0;
async function review(){
 const id=new URL(location.href).searchParams.get('cmMemo');if(!/^[a-f0-9]{24}$/.test(id||''))return;
 const seq=++reviewTicket;
 try{
  const item=(await request(null,'?id='+id)).items[0];if(seq!==reviewTicket)return;
  let minimized=false;try{minimized=localStorage.getItem('cm-review-minimized')==='1';}catch{}
  const previous=document.getElementById('cmReview'),wasOpen=previous?.querySelector('details')?.open??!minimized;
  previous?.remove();if(!item)return;
  const done=!!item.doneAt,p=document.createElement('aside');p.id='cmReview';p.classList.toggle('cm-review-done',done);p.classList.add('cm-'+resultState(item));
  p.innerHTML=`<details ${wasOpen?'open':''}><summary title="クリックで最小化・展開"><span class="cm-review-label">CODEXメモ · ${done?'対応完了':statusLabel(item)}${item.responses?.length?' · 回答・対応結果あり':''}</span><span class="cm-review-toggle">${wasOpen?'− 最小化':'＋ 開く'}</span></summary><p class="cm-review-guide">${done?'このメモは対応完了として記録されています。':'このメモの修正確認で開いたページです。内容を確認し、直っていれば「対応完了」、追加の報告は「追記」を押してください。'}</p><p class="cm-review-topic"><b>${esc(item.pageTitle)}</b><br>${esc(item.text)||'画像のメモです。一覧で確認してください。'}</p>${(item.updates||[]).length?'<p><b>最新の追記</b><br>'+esc(item.updates.at(-1).text||'画像の追記')+'</p>':''}${responseHtml(item)}${done?'<p class="cm-review-confirmed">確認：'+esc(item.doneBy)+' · '+date(item.doneAt)+'</p>':''}<div class="cm-review-actions">${statusSelect(item)}<button type="button" class="ws-button primary" data-done ${done?'disabled':''}>${done?'✓ 対応完了':'対応完了'}</button><button type="button" class="ws-button" data-append>追記</button><a href="codex_memos.php" target="_blank" rel="noopener">メモ一覧</a></div><small class="cm-review-new-hint">別の内容は、いつもの「✎ CODEXメモ」アイコンから新規メモを書けます。</small><span role="status"></span></details>`;
  const details=p.querySelector('details');p.classList.toggle('cm-minimized',!wasOpen);
  details.addEventListener('toggle',()=>{p.classList.toggle('cm-minimized',!details.open);p.querySelector('.cm-review-toggle').textContent=details.open?'− 最小化':'＋ 開く';try{localStorage.setItem('cm-review-minimized',details.open?'0':'1');}catch{}});
  document.body.append(p);p.querySelector('[data-memo-status]').onchange=async e=>{e.target.disabled=true;try{await request({action:'status',id:item.id,version:item.version,status:e.target.value});changed();}catch(err){p.querySelector('[role=status]').textContent=err.message;e.target.value=memoStatus(item);e.target.disabled=false;}};p.querySelector('[data-append]').onclick=()=>compose({item});p.querySelector('[data-history-copy]').onclick=()=>copy([item],p.querySelector('[role=status]'));p.querySelector('[data-history-zip]').onclick=async e=>{e.target.disabled=true;try{await download([item],p.querySelector('[role=status]'),true);}catch(err){p.querySelector('[role=status]').textContent=err.message;}finally{e.target.disabled=false;}};
  p.querySelector('[data-done]').onclick=async e=>{e.target.disabled=true;try{await mark(item,true);toast('対応完了として記録しました。未対応の一覧から非表示になります。');}catch(err){p.querySelector('[role=status]').textContent=err.message;e.target.disabled=false;}};
 }catch(e){toast(e.message);}
}
function boot(){
 if(StaffAuth.user?.role!=='admin'||StaffAuth.user.mustChange||window.top!==window.self)return;
 const style=document.createElement('link');style.rel='stylesheet';style.href='codex-memos.css?v=20260916-r54-ready';if(!document.querySelector('link[href^="codex-memos.css"]'))document.head.append(style);
 const savebar=document.querySelector('.group-savebar');if(savebar){const place=()=>document.documentElement.style.setProperty('--cm-footer-space',(Math.ceil(savebar.getBoundingClientRect().height)+28)+'px');new ResizeObserver(place).observe(savebar);place();}
 const launcher=document.createElement('button');launcher.type='button';launcher.id='cmLauncher';launcher.textContent='✎ CODEXメモ';launcher.title='新規のCODEXメモを書く';launcher.onclick=()=>compose();document.body.append(launcher);
 // Native dialogs make the rest of the page inert; provide the same action inside them.
 const observe=()=>{for(const toolbar of document.querySelectorAll('.db-tools')){if(toolbar.querySelector('.cm-board-launch'))continue;const b=document.createElement('button');b.type='button';b.className='ws-button cm-board-launch';b.textContent='CODEXメモ';b.onclick=()=>compose();toolbar.append(b);}for(const d of document.querySelectorAll('dialog[open]:not([data-cm-dialog])')){if(d.querySelector('.cm-context-launch'))continue;const b=document.createElement('button');b.type='button';b.className='cm-context-launch';b.textContent='✎ CODEXメモ';b.onclick=()=>compose();const head=d.querySelector('.sc-head,.db-edit-head,.ws-dialog-head,.dialog-head,header');(head||d).append(b);}};
 new MutationObserver(observe).observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:['open']});observe();listPage();review();window.addEventListener('codex-memo-changed',review);window.addEventListener('focus',review);window.addEventListener('storage',e=>{if(e.key==='codex-memo-change')review();});
}
window.CodexMemos={compose};StaffAuth.ready.then(()=>{if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();});
})();
