(()=>{'use strict';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Tokyo'}),difference=(a,b)=>Math.round((Date.parse(a+'T00:00:00Z')-Date.parse(b+'T00:00:00Z'))/86400000);
const params=new URLSearchParams(location.search);document.body.classList.toggle('countdown-embed',params.get('embed')==='1');let events=[],page=0,loading=false,paused=false,loadedDay='',school=params.get('school')||'';
function render(){const date=today(),list=events.filter(e=>['test','exam','mock'].includes(e.category)&&e.startDate>=date&&(!school||e.kind==='notice'||e.schoolId===school)).sort((a,b)=>a.startDate.localeCompare(b.startDate)||a.title.localeCompare(b.title,'ja')),pages=Math.max(1,Math.ceil(list.length/3));page=(page+pages)%pages;
 $('countdownRows').innerHTML=list.slice(page*3,page*3+3).map(e=>{const days=difference(e.startDate,date);return `<a class="countdown-row" href="notices.html?id=${encodeURIComponent(e.id)}" target="_top"><div><span class="countdown-target">${esc(e.schoolName||(e.targetClasses||[]).join('・')||'全員')}</span><h2>${esc(e.title)}</h2><small>${esc(e.startDate)}${e.schoolName&&(e.targetClasses||[]).length?' ／ '+esc(e.targetClasses.join('・')):''}</small></div><div class="countdown-number"><span>${days?'あと':'いよいよ'}</span><strong>${days||'本日'}</strong>${days?'<span>日</span>':''}</div></a>`;}).join('')||'<p class="countdown-empty">公開中のテスト・入試・模試の予定はありません。</p>';
 $('countdownPage').textContent=list.length+'件 ／ '+(page+1)+' / '+pages;$('countdownPrevious').disabled=$('countdownNext').disabled=pages<2;$('countdownPause').hidden=pages<2;
}
async function load(){if(loading)return;loading=true;const c=new AbortController(),timer=setTimeout(()=>c.abort(),15000);try{const response=await fetch('calendar_events_api.php',{cache:'no-store',signal:c.signal}),j=await response.json();if(!response.ok||!j.ok)throw Error();events=j.events;loadedDay=today();$('countdownSchool').innerHTML='<option value="">すべて</option>'+j.schools.map(s=>`<option value="${esc(s.id)}">${esc(s.name)}</option>`).join('');$('countdownSchool').value=school;$('countdownStatus').textContent='基準日 '+loadedDay+' ／ 確認 '+new Date().toLocaleTimeString('ja-JP',{timeZone:'Asia/Tokyo',hour:'2-digit',minute:'2-digit'})+'（30秒ごとに更新）';render();}catch{$('countdownStatus').textContent='最新情報を確認できません。通信を確認してください。'+(events.length?' 前回取得した予定を表示しています。':'');}finally{clearTimeout(timer);loading=false;}}
 $('countdownSchool').onchange=e=>{school=e.target.value;page=0;render();};$('countdownPrevious').onclick=()=>{page--;render();};$('countdownNext').onclick=()=>{page++;render();};$('countdownPause').onclick=e=>{paused=!paused;e.target.textContent=paused?'再生':'一時停止';};$('countdownFullscreen').onclick=()=>{if(document.fullscreenElement)document.exitFullscreen();else document.documentElement.requestFullscreen().catch(()=>{});};
 setInterval(()=>{if(!document.hidden&&!paused){page++;render();}if(loadedDay!==today())load();},10000);setInterval(load,30000);window.addEventListener('focus',load);load();
})();