(()=>{'use strict';
const iso=d=>String(d).replaceAll('/','-'),shift=(d,n)=>new Date(Date.parse(d+'T00:00:00Z')+n*86400000).toISOString().slice(0,10);
let enabled=false,from='',to='';
function layout(){const grid=document.querySelector('#grid .generator-grid');if(!grid)return;const cells=[...grid.querySelectorAll('.generator-slot')];for(const card of grid.querySelectorAll('.generator-linked-card')){const cell=card.closest('.generator-slot'),slots=JSON.parse(card.dataset.linkedSlots),last=cells.find(c=>c.dataset.date===cell.dataset.date&&c.dataset.room===cell.dataset.room&&c.dataset.slot===slots.at(-1));if(last)card.style.setProperty('width',Math.max(0,last.getBoundingClientRect().right-card.getBoundingClientRect().left-7)+'px');}}
function dropCell(cell,x){const grid=cell.closest('.generator-grid'),heads=[...grid.querySelectorAll(':scope > .head')].slice(1),i=heads.findIndex(h=>{const r=h.getBoundingClientRect();return x>=r.left&&x<r.right;});return i<0?cell:[...grid.querySelectorAll('.generator-slot')].find(c=>c.dataset.date===cell.dataset.date&&c.dataset.room===cell.dataset.room&&c.dataset.slot===[...'①②③④⑤⑥⑦⑧⑨⑩⑪'][i])||cell;}
window.DayCompare={dropCell,get active(){return enabled;},dates:()=>[from,to],showRoom:(room,rows)=>document.getElementById("compareEmptyRooms")?.checked||rows.some(r=>((v)=>["","青","黄","白","ガラス","PC","自宅可"].includes(v)?v:"__OTHER__")(String(r["教室"]||"").trim())===room)||(rows.length===0&&room==="青"),layout};
function install(){const bar=document.getElementById('generatorDateNavigation');if(!bar){setTimeout(install,100);return;}const panel=document.createElement('details');panel.id='dayCompare';panel.innerHTML='<summary>2日を上下で比較・コピー</summary><div class="dc-tools"><label>上：参考にする日<input type="date" id="compareFrom"><span class="dc-weekday" id="compareFromWeekday"></span></label><label>下：予定を組む日<input type="date" id="compareTo"><span class="dc-weekday" id="compareToWeekday"></span></label><button type="button" id="compareShow">上下に表示</button><button type="button" id="compareCopy" disabled>上の日を下の日へコピー</button><button type="button" id="compareEnd" hidden>通常表示に戻す</button><label class="dc-empty"><input type="checkbox" id="compareEmptyRooms">空き教室も表示</label><span id="compareMessage" role="status"></span></div>';bar.append(panel);const $=id=>document.getElementById(id),initial=iso(new URL(location.href).searchParams.get('linkedDate')||HistoryWindow.start());$('compareTo').value=initial;$('compareFrom').value=shift(initial,-7);const weekdays=()=>{for(const id of ['compareFrom','compareTo']){const value=$(id).value;$(id+'Weekday').textContent=value?new Date(value+'T12:00:00+09:00').toLocaleDateString('ja-JP',{month:'long',day:'numeric',weekday:'long',timeZone:'Asia/Tokyo'}):'';}};weekdays();panel.addEventListener('input',weekdays);
 $('compareShow').onclick=()=>{from=$('compareFrom').value;to=$('compareTo').value;if(!from||!to||from===to){$('compareMessage').textContent='異なる2日を指定してください。';return;}enabled=true;document.body.classList.add('dc-active');$('compareCopy').disabled=false;$('compareEnd').hidden=false;$('compareMessage').textContent='上：参考日 ／ 下：調整日。コマをクリックして編集できます。';Generator.render();window.GeneratorView?.scrollStart();};
 $('compareEmptyRooms').onchange=()=>{if(enabled)Generator.render();};
 $('compareCopy').onclick=async()=>{try{await WeekCopy.open(from,to);}catch(e){$('compareMessage').textContent=e.message;}};
 $('compareEnd').onclick=()=>{enabled=false;document.body.classList.remove('dc-active');$('compareEnd').hidden=true;$('compareCopy').disabled=true;$('compareMessage').textContent='';Generator.render();};
 document.addEventListener('history-window-change',()=>{if(enabled){enabled=false;document.body.classList.remove('dc-active');$('compareEnd').hidden=true;$('compareCopy').disabled=true;Generator.render();}});
 document.addEventListener('change',e=>{if(e.target.matches('#compareFrom,#compareTo'))$('compareCopy').disabled=true;});
 window.addEventListener('resize',layout);new ResizeObserver(layout).observe(document.getElementById('gridWrap'));}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
