<?php
require_once __DIR__.'/staff_security.php';header('Cache-Control: private, no-store, no-cache, must-revalidate, max-age=0');header('Vary: Cookie');
$viewer=staffCurrent();if(!$viewer){$returnPage='incident_reports.php';if(preg_match('/^[a-f0-9]{24}$/',(string)($_GET['id']??'')))$returnPage.='?id='.$_GET['id'];header('Location: staff_login.html?next='.rawurlencode($returnPage),true,303);exit;}if($viewer['mustChange']){header('Location: staff_account.html',true,303);exit;}staffRequire();
header('Content-Type: text/html; charset=utf-8');
?>
<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>トラブル・来客の報告</title><link rel="stylesheet" href="workspace-ui.css?v=20260912-r24"><link rel="stylesheet" href="incident-reports.css?v=20260911-r16"><script src="staff-auth.js?v=20260917-r56-ready" data-staff="required"></script><script defer src="workspace-ui.js?v=20260916-r54-ready"></script></head><body><main class="workspace-page incidents-page">
<div class="incident-heading"><div><h1>トラブル・来客の報告</h1><p class="lede">起きたこと・対応したことを記録します。閲覧範囲は投稿者が選べます。</p></div><button id="incidentNew" type="button" class="ws-button primary">＋ 報告を作成</button><button id="tuitionNew" type="button" class="ws-button">月謝を預かった</button></div>
<p class="incident-related"><a href="system_updates.php#staffRequestSection">依頼・相談は「連絡・要望」へ</a></p><div id="incidentCounts" class="incident-counts" aria-live="polite"></div>
<div class="incident-filters"><label>検索<input id="incidentSearch" type="search" placeholder="件名・内容・関係者・報告者"></label><label>種類<select id="incidentCategory"><option value="">すべて</option><option value="trouble">トラブル</option><option value="visitor">来客</option><option value="parent">保護者対応</option><option value="facility">設備・備品</option><option value="other">その他</option><option value="tuition">月謝預かり</option></select></label><label>対応状況<select id="incidentStatus"><option value="">すべて</option><option value="pending">未対応・対応中</option><option value="open">未対応</option><option value="in_progress">対応中</option><option value="resolved">対応済み</option><option value="information">記録のみ</option></select></label><label>発生日から<input id="incidentFrom" type="date"></label><label>発生日まで<input id="incidentTo" type="date"></label><label id="incidentHiddenLabel" hidden><input id="incidentShowHidden" type="checkbox">非表示も表示</label><button id="incidentReload" type="button" class="ws-button">再読み込み</button></div>
<p id="incidentListMessage" class="ws-message" role="status"></p><div id="incidentList" class="incident-list"></div><button id="incidentMore" type="button" class="ws-button" hidden>さらに30件表示</button>
</main><dialog id="incidentDialog" class="incident-dialog" aria-labelledby="incidentDialogTitle"></dialog><script defer src="incident-reports.js?v=20260915-r44"></script></body></html>
