(()=>{
let groups=[];const url=id=>{const u=new URL('lesson_group.html',location.href);u.searchParams.set('v','20260916-r53');u.searchParams.set('id',id);const from=window.GroupScheduleActions?.origin()||location.pathname.split('/').pop()+location.search;if(/^(?:schedule_generator\.(?:html|php)|teacher2026summer(?:_vertical)?\.html)(?:\?[^#]*)?$/.test(from))u.searchParams.set('returnTo',from);return u.pathname.split('/').pop()+u.search;};
async function refresh(){await StaffAuth.ready;const r=await fetch('lesson_group_api.php?action=index',{cache:'no-store'}),j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||'連結情報を読み込めません');groups=j.groups||[];return groups;}
const forKey=key=>groups.find(g=>g.key===key||g.lessonKeys.includes(key)),forSource=source=>groups.find(g=>g.sources.includes(source));
const returnToGenerator=(g,origin)=>GroupScheduleActions.returnToSchedule(g,origin);
window.LessonGroups={refresh,forKey,forSource,url,returnToGenerator,get groups(){return groups;}};
LessonGroups.ready=refresh();LessonGroups.ready.catch(e=>console.warn(e.message));
async function create(source){
 const returnTarget=GroupScheduleActions.origin();
 if(StaffAuth.user?.role!=='admin')return;if(window.Generator?.hasDraft()){alert('詳細に未保存の変更があります。先に保存してから連結してください。');return;}const esc=Workspace.esc;let d=document.getElementById('linkLessonDialog');if(!d){d=document.createElement('dialog');d.id='linkLessonDialog';d.className='ws-dialog';document.body.appendChild(d);}
 d.innerHTML='<div class="ws-dialog-inner"><div class="ws-dialog-head"><h2>連続するコマを連結</h2><button id="linkLessonClose" class="ws-button">閉じる</button></div><div class="ws-dialog-body"><p>同じ日の連続する授業を1つの詳細・出席・カルテ・報告や返信にまとめます。給与は元のコマ数で計算します。コマのエリアを押して選択・解除できます。</p><label class="ws-form">途中の食事休憩<select id="linkLessonMealBreak"><option value="0">なし</option><option value="1">あり（途中で食事休憩が入ります）</option></select></label><div id="linkLessonCandidates">読み込み中…</div></div><div class="ws-dialog-foot"><span id="linkLessonMessage" class="ws-message" role="status"></span><button id="linkLessonSave" class="ws-button primary" disabled>選んだコマを連結</button></div></div>';d.showModal();let busy=false;d.oncancel=e=>{if(busy)e.preventDefault();};d.querySelector('#linkLessonClose').onclick=()=>{if(!busy)d.close();};
 try{const j=await Workspace.api('lesson_group_api.php?action=candidates&sourceKey='+encodeURIComponent(source));const candidates=j.candidates||[];d.querySelector('#linkLessonCandidates').innerHTML=candidates.map(c=>`<article class="ws-card link-lesson-option"><label class="link-lesson-select"><span class="ws-check"><input type="checkbox" data-link-source="${esc(c.row._sourceKey)}" ${c.row._sourceKey===source?'checked':''}><b>${esc(c.row['時間番号'])} ${esc(c.row['開始'])}–${esc(c.row['終了'])} ${esc(c.row['クラス'])}</b></span>${!c.record.memo?'<small class="ws-muted">カルテ未入力</small>':''}</label>${c.record.memo?`<details><summary>現在のカルテを確認</summary><p>${esc(c.record.memo)}</p><small>${esc(c.record.author||c.record.teacher||'')}</small></details>`:''}</article>`).join('');d.querySelector('#linkLessonSave').disabled=candidates.length<2;if(candidates.length<2)d.querySelector('#linkLessonMessage').textContent='連結できる同じ授業がありません。先にコマを配置してください。';
 d.querySelector('#linkLessonSave').onclick=async()=>{const sources=[...d.querySelectorAll('[data-link-source]:checked')].map(e=>e.dataset.linkSource);busy=true;d.querySelectorAll('button,input,select').forEach(e=>e.disabled=true);try{const result=await Workspace.api('lesson_group_api.php',{action:'create',sources,version:j.version,mealBreak:d.querySelector('#linkLessonMealBreak').value==='1'});returnToGenerator(result.group,returnTarget);}catch(e){d.querySelector('#linkLessonMessage').textContent=e.message;}finally{busy=false;d.querySelectorAll('button,input,select').forEach(e=>e.disabled=false);}};
 }catch(e){d.querySelector('#linkLessonMessage').textContent=e.message;}
}
document.addEventListener('click',e=>{const setup=e.target.closest('[data-link-lesson]');if(setup){e.preventDefault();e.stopPropagation();create(setup.dataset.linkLesson);return;}if(!StaffAuth.user)return;const card=e.target.closest('#gridWrap .lesson,#schedule .event[data-key]');if(!card||e.target.closest('button,input,select,a,.lesson-list-actions'))return;const source=card.dataset.sourceKey||card.dataset.source||'',key=card.dataset.key||card.querySelector('[data-lesson-key]')?.dataset.lessonKey,g=forSource(source)||forKey(key);if(g){e.preventDefault();e.stopImmediatePropagation();location.assign(url(g.id));}},true);
function mark(){document.querySelectorAll('#gridWrap .lesson,#schedule .event[data-key]').forEach(c=>{const key=c.dataset.key||c.querySelector('[data-lesson-key]')?.dataset.lessonKey,g=forSource(c.dataset.sourceKey||c.dataset.source||'')||forKey(key);let badge=c.querySelector('.lesson-group-link');let setup=c.querySelector('.lesson-group-create');let meal=c.querySelector('.lesson-group-meal');if(g?.mealBreak&&c.closest('#gridWrap')){if(!meal){meal=document.createElement('span');meal.className='lesson-group-meal';meal.textContent='🍴';meal.title='途中で食事休憩が入ります';meal.setAttribute('aria-label',meal.title);(c.querySelector('strong,.event-title')||c).appendChild(meal);}}else meal?.remove();if(!g){badge?.remove();const source=c.dataset.sourceKey||c.dataset.source||'';if(StaffAuth.user?.role==='admin'&&source&&!setup){setup=document.createElement('button');setup.type='button';setup.className='lesson-group-create';setup.dataset.linkLesson=source;setup.textContent='🔗';setup.title='連続するコマを連結';setup.setAttribute('aria-label',setup.title);(c.querySelector('strong,.event-title')||c).prepend(setup);}return;}setup?.remove();if(!badge){badge=document.createElement('a');badge.className='lesson-group-link';(c.querySelector('strong,.event-title')||c).prepend(badge);}badge.href=url(g.id);if(badge.textContent!=='🔗')badge.textContent='🔗';badge.title=g.slots+'の連結詳細を開く';badge.setAttribute('aria-label',badge.title);});}
LessonGroups.ready.then(()=>{const run=()=>{mark();const area=document.getElementById('gridWrap')||document.getElementById('schedule');if(area){let queued=false;new MutationObserver(()=>{if(queued)return;queued=true;setTimeout(()=>{queued=false;mark();},60);}).observe(area,{childList:true,subtree:true});}};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run);else run();}).catch(()=>{});
})();
