(()=>{
const $=id=>document.getElementById(id),esc=Workspace.esc,id=new URLSearchParams(location.search).get('id');let data=null,busy=false,dirty=false;
function status(){const el=$('groupDirtyStatus');if(el)el.textContent=dirty?'未保存の変更があります':data?.group.active?'保存済み':'確認中';}
function changed(){dirty=true;status();requiredFields();}
const message=(s,error=false)=>{$('groupMessage').textContent=s;$('groupMessage').classList.toggle('error',error);status();};
function requiredFields(){
 if(!data?.group.active){$('groupRequiredSummary').hidden=true;document.querySelectorAll('.group-field-help').forEach(el=>el.hidden=true);document.querySelectorAll('.group-field-missing').forEach(el=>{el.classList.remove('group-field-missing');el.setAttribute('aria-invalid','false');});return [];}
 const end=new Date(data.group.date+'T'+data.group.end+':00'),due=Number.isFinite(end.getTime())&&end<=new Date(),missing=[];
 const mark=(field,text,id)=>{let hint=document.getElementById(id);if(!hint){hint=document.createElement('p');hint.id=id;hint.className='group-field-help';field.insertAdjacentElement('afterend',hint);}hint.textContent=text;hint.hidden=!text;field.classList.toggle('group-field-missing',!!text);field.setAttribute('aria-invalid',text&&due?'true':'false');field.setAttribute('aria-describedby',id);};
 for(const [id,title,tip] of [['groupMemo','カルテ','授業で取り組んだ内容や生徒の様子を記入してください。'],['groupHomework','宿題','宿題を記入してください。出さない日は「宿題なしを入力」を押してください。']]){const field=$(id),empty=!field.value.trim();mark(field,empty?(due?'未記入：':'授業後に記録：')+tip:'',id+'Help');if(empty)missing.push({id,title});}
 document.querySelectorAll('[data-group-attendance]').forEach((field,i)=>{const name=field.dataset.groupAttendance,value=field.value;const slots=data.members.filter(m=>{const stored=value||m.state.attendance?.[name]||(Workspace.exempt(name,data.group.className,data.group.date,m.state)?'免除':'---');return !['出席','遅刻','欠席','早退','免除','その他','不明','未定'].includes(stored);}).map(m=>m.row['時間番号']);field.id='groupAttendanceField'+i;const message=slots.length?(due?'出欠未登録：':'授業後に出欠を登録：')+slots.join('')+'の出欠を選んでください。':'';mark(field,message,'groupAttendanceHelp'+i);field.closest('.group-att-row').classList.toggle('has-required-gap',!!message);if(slots.length)missing.push({id:field.id,title:name+'の出欠（'+slots.join('')+'）'});});
 missing.sort((a,b)=>$(a.id).compareDocumentPosition($(b.id))&Node.DOCUMENT_POSITION_FOLLOWING?-1:1);
 const box=$('groupRequiredSummary');box.hidden=!missing.length;box.innerHTML=missing.length?'<strong>'+(due?'未記入の箇所':'授業後に記録する箇所')+' '+missing.length+'件</strong><p>入力済みの内容は途中でも保存できます。保存するまでは記録に反映されません。</p><div>'+missing.map(m=>'<button type="button" class="group-required-jump" data-required-target="'+esc(m.id)+'">'+esc(m.title)+'へ</button>').join('')+'</div>':'';
 return missing;
}

function lock(on){busy=on;document.querySelectorAll('#groupContent button,#groupContent input,#groupContent select,#groupContent textarea,#groupSave,#groupReload,#groupDelete').forEach(e=>e.disabled=on||!data?.group.active);$('groupReload').disabled=on;}
async function files(){await StudentAttachments.loadAll();const keys=new Set([data.group.key,...data.members.map(m=>m.key)]);const all=Object.entries(StudentAttachments.all()).filter(([key])=>keys.has(key)).flatMap(([,v])=>v);const unique=[...new Map(all.map(f=>[f.id,f])).values()];$('groupFileCount').textContent=unique.length+'件';$('groupFiles').innerHTML=unique.map(f=>`<p><a href="${StudentAttachments.rawUrl(f)}">${esc(f.name)}</a> <small>${esc(f.senderName||'')}</small></p>`).join('')||'<p class="ws-muted">添付資料はありません。</p>';}
function render(){window.RecordingTools?.repairGroup();const g=data.group;$('groupTests').href='test_results.html?new=1&key='+encodeURIComponent(g.key);const back=document.querySelector('.workspace-page>a.ws-button');if(back){document.querySelector('.group-page-actions').append(back);const dest=GroupScheduleActions.origin();if(StaffAuth.user?.role==='admin'||!dest.startsWith('schedule_generator'))back.href=dest;back.textContent='← 時間割に戻る';}$('groupHeading').textContent=g.className;$('groupSummary').textContent=g.date+' · '+g.slots+' 連結授業'+(g.active?'':'（連結解除済み・履歴）');$('groupFacts').innerHTML=[['時間',g.start+'–'+g.end],['担当',g.teacher||'未設定（管理者）'],['教室',g.room||'未設定'],['コマ数',g.sources.length+'コマ分']].map(([label,value])=>'<div><small>'+label+'</small><strong>'+esc(value)+'</strong></div>').join('')+(g.mealBreak?'<p class="group-meal">途中で食事休憩が入ります</p>':'');const notes=[...new Set(data.members.map(m=>m.state.publicNote??m.row['備考']??'').filter(Boolean))];$('groupPublicNote').value=notes.join('\n\n');$('groupPublicNote').dataset.initial=$('groupPublicNote').value;$('groupMemo').value=data.record.memo||'';$('groupHomework').value=data.record.homework||'';$('groupClassSchedule').href=Workspace.classLink(g.className);$('groupRecords').href='lesson_records.html?class='+encodeURIComponent(g.className);$('groupDelete').hidden=$('groupUnlink').hidden=$('groupLengthen').hidden=$('groupExtend').hidden=!g.active||StaffAuth.user?.role!=='admin';
 $('groupAttendance').innerHTML=data.students.map(name=>{const values=data.members.map(m=>m.state.attendance?.[name]|| (Workspace.exempt(name,g.className,g.date,m.state)?'免除':'---'));const common=values.every(v=>v===values[0])?values[0]:'';return `<div class="group-att-row"><strong>${esc(name)}</strong><span class="ws-muted">${common?('現在：'+esc(common)):data.members.map((m,i)=>esc(m.row['時間番号'])+'：'+esc(values[i])).join(' / ')}</span><select aria-label="${esc(name)}の出欠" data-group-attendance="${esc(name)}" data-current-exempt="${values.includes('免除')}" data-initial-value="${esc(common)}"><option value="">コマごとに異なる（変更しない）</option>${['---','出席','遅刻','欠席','早退','免除','その他','不明','未定'].map(v=>`<option value="${v}" ${v===common?'selected':''}>${v}</option>`).join('')}</select></div>`;}).join('')||'<p>参加生徒はありません。</p>';
 const missingNames=data.students.filter(name=>data.members.some(m=>{const value=m.state.attendance?.[name];return !['出席','遅刻','欠席','早退','免除','その他','不明','未定'].includes(value)&&!Workspace.exempt(name,g.className,g.date,m.state);}));$('groupProgress').innerHTML=[['groupAttendanceSection','出欠',missingNames.length?'未登録 '+missingNames.length+'名':data.members.some(m=>Object.values(m.state.attendance||{}).includes('未定'))?'未定あり':'記録済み',!!missingNames.length],['groupRecordSection','カルテ',data.record.memo?.trim()==='未定'?'未定':data.record.memo?.trim()?'記入済み':'未記入',!data.record.memo?.trim()],['groupRecordSection','宿題',data.record.homework?.trim()==='未定'?'未定':data.record.homework?.trim()?'記入済み':'未記入',!data.record.homework?.trim()]].map(([anchor,label,state,missing])=>`<a href="#${anchor}" class="${missing?'is-missing':'is-complete'}"><b>${label}</b><span>${state}</span></a>`).join('');window.RecordingTools?.context(g.key,$('groupRecordSection'),true);$('groupReplyCount').textContent=(data.record.replies||[]).length+'件';
 $('groupOriginals').innerHTML=data.members.map(m=>`<article class="ws-card"><strong>${esc(m.row['時間番号'])} ${esc(m.row['開始'])}–${esc(m.row['終了'])}</strong><div class="group-original">${esc(m.record.memo||'カルテ未入力')}</div>${m.record.homework?'<p>宿題：'+esc(m.record.homework)+'</p>':''}<small>${esc(m.record.author||m.record.teacher||'')}</small><div>${(m.record.replies||[]).map(r=>`<p>${esc(r.author)}：${esc(r.text)}</p>`).join('')}</div><p class="ws-muted">よみました：${esc(Object.keys(m.record.reads||{}).join('、')||'なし')}</p></article>`).join('');
 $('groupReplies').innerHTML=(data.record.replies||[]).map(r=>`<article class="ws-card"><b>${esc(r.author)}</b><p>${esc(r.text)}</p></article>`).join('')+'<p class="ws-muted">よみました：'+esc(Object.keys(data.record.reads||{}).join('、')||'なし')+'</p>';$('groupReady').value='';$('groupContent').hidden=false;SharedNotes.mount($('groupSharedMemo'),g.className);dirty=false;
 const scRoot=$('scGroupContacts');scRoot.innerHTML='';delete scRoot._scInbox;if(g.active&&window.StaffContacts)StaffContacts.mount(scRoot,{keys:data.members.map(m=>m.key),beforeConfirm:()=>{if(dirty)throw Error('編集中のカルテや出欠を先に「まとめて保存」してから確定してください。');lock(true);},onConfirmed:async()=>{busy=false;await load();},onFinally:()=>lock(false)});
 requiredFields();
}
async function load(){if(busy)return false;if(dirty&&!confirm('未保存の変更を取り消して再読み込みしますか？'))return false;lock(true);message('読み込み中…');try{await Workspace.refresh();data=await Workspace.api('lesson_group_api.php?action=detail&id='+encodeURIComponent(id||''));render();await files();message(data.group.active?'':'連結中の記録を履歴として表示しています。');return true;}catch(e){data=null;message(e.message,true);return false;}finally{lock(false);}}
async function save(){if(!data?.group.active)return false;const attendance={};document.querySelectorAll('[data-group-attendance]').forEach(s=>{if(s.value!==''&&s.value!==s.dataset.initialValue)attendance[s.dataset.groupAttendance]=s.value;});const ready=$('groupReady').value;lock(true);message('保存中…');try{await SharedNotes.post(data.group.className,$('groupSharedMemo'));await Workspace.api('lesson_group_api.php',{action:'save',id,version:data.version,memo:$('groupMemo').value,homework:$('groupHomework').value,attendance,...($('groupPublicNote').value!==$('groupPublicNote').dataset.initial?{publicNote:$('groupPublicNote').value}:{}),...(ready?{ready:ready==='yes'}:{})});dirty=false;busy=false;if(!await load()){message('保存は完了しましたが、再読み込みに失敗しました。「再読み込み」で確認してください。',true);return false;}message('連結した授業の内容を保存しました。');return true;}catch(e){message(e.message,true);return false;}finally{lock(false);}}
$('groupSharedMemoPost').onclick=async()=>{try{await SharedNotes.post(data.group.className,$('groupSharedMemo'));$('groupSharedMemoMessage').textContent='発言者と日時を記録しました。';}catch(e){$('groupSharedMemoMessage').textContent=e.message;}};
$('groupRequiredSummary').onclick=e=>{const id=e.target.closest('[data-required-target]')?.dataset.requiredTarget;if(id){$(id).scrollIntoView({block:'center',behavior:'smooth'});$(id).focus({preventScroll:true});}};
$('groupSave').onclick=save;$('groupReload').onclick=load;document.addEventListener('input',e=>{if(e.target.closest('#groupContent')&&!e.target.closest('.shared-notes-list,.shared-notes-toolbar,.sc-inbox')&&!['groupReplyText','groupFileInput'].includes(e.target.id))changed();});document.addEventListener('change',e=>{if(e.target.closest('#groupContent')&&!e.target.closest('.shared-notes-list,.shared-notes-toolbar,.sc-inbox')&&!['groupReplyText','groupFileInput'].includes(e.target.id))changed();});window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
$('groupAllPresent').onclick=()=>{document.querySelectorAll('[data-group-attendance]').forEach(s=>s.value='出席');changed();message('全員を出席にしました。「まとめて保存」で確定します。');};
$('groupLengthen').onclick=()=>{if(dirty){message('編集中のカルテや出欠を先に「まとめて保存」してください。',true);return;}GroupScheduleActions.lengthen(id);};
$('groupExtend').onclick=()=>{if(dirty){message('編集中のカルテや出欠を先に「まとめて保存」してください。',true);return;}GroupScheduleActions.extend(id);};
$('groupDelete').onclick=async()=>{if(!data?.group.active||busy)return;if(!confirm(data.group.date+' '+data.group.slots+' '+data.group.className+' の全'+data.group.sources.length+'コマの予定を削除しますか？出欠・カルテ・返信は保持します。未保存の入力は保存されません。'))return;lock(true);try{await Workspace.api('lesson_group_api.php',{action:'delete',id,version:data.version});GroupScheduleActions.returnToSchedule(data.group);}catch(e){message(e.message,true);}finally{lock(false);}};
$('groupUnlink').onclick=async()=>{if(dirty&&!await save())return;if(!confirm('連結を解除しますか？共通カルテは履歴に残り、各コマを個別に編集できるようになります。'))return;lock(true);try{await Workspace.api('lesson_group_api.php',{action:'unlink',id,version:data.version});dirty=false;busy=false;await load();}catch(e){message(e.message,true);}finally{lock(false);}};
for(const [button,action] of [['groupReply','reply'],['groupRead','read']])$(button).onclick=async()=>{if(dirty&&!await save())return;lock(true);try{await Workspace.api('lesson_record_api.php',{action,eventKey:data.group.key,text:$('groupReplyText').value});$('groupReplyText').value='';busy=false;await load();}catch(e){message(e.message,true);}finally{lock(false);}};
$('groupFileUpload').onclick=async()=>{lock(true);try{for(const file of $('groupFileInput').files)await StudentAttachments.upload(data.group.key,file);$('groupFileInput').value='';await files();message('資料を保存しました。');}catch(e){message(e.message,true);}finally{lock(false);}};
StaffAuth.ready.then(load).catch(e=>message(e.message,true));
})();
