(()=>{
const root=document.getElementById('lessonTasks');if(!root)return;
const labels={attendance:'出欠未登録',memo:'カルテ未記入',homework:'宿題未記入'},actions={attendance:'出欠を登録',memo:'カルテを記入',homework:'宿題を記入'};
let items=[],limit=20,request=0,active=false,admin=false,mineCount=null,version='',busy=false,selected=new Map();
const $=id=>root.querySelector('#'+id),esc=s=>Workspace.esc(s);
function filtered(){if(admin&&$('lessonTaskFrom').value&&$('lessonTaskUntil').value&&$('lessonTaskFrom').value>$('lessonTaskUntil').value)return [];const chosenClass=$('lessonTaskClass').value,kind=$('lessonTaskKind').value,q=$('lessonTaskSearch').value.trim().toLocaleLowerCase(),excluded=admin&&$('lessonTaskDisplay').value==='excluded';return items.filter(r=>(!chosenClass||r.className===chosenClass)&&!!r.excluded===excluded&&(!kind||r.missing.includes(kind))&&(!q||[r.className,r.teacher,r.date,r.slots].join(' ').toLocaleLowerCase().includes(q))&&(!admin||((!$('lessonTaskFrom').value||r.date>=$('lessonTaskFrom').value)&&(!$('lessonTaskUntil').value||r.date<=$('lessonTaskUntil').value)&&(!$('lessonTaskTeacher').value||r.teacher===$('lessonTaskTeacher').value||($('lessonTaskTeacher').value==='__unset__'&&!r.teacher))&&(!$('lessonTaskClass').value||r.className===$('lessonTaskClass').value))));}
function taskOrder(a,b){const first=(a.date+' '+a.end+' '+a.start).localeCompare(b.date+' '+b.end+' '+b.start)||a.className.localeCompare(b.className,'ja')||a.key.localeCompare(b.key);return $('lessonTaskSort').value==='asc'?first:-first;}
function selection(){if(!admin)return;$('lessonTaskSelected').textContent=selected.size+'件選択';$('lessonTaskApply').disabled=$('lessonTaskTbd').disabled=busy||!selected.size;$('lessonTaskApply').textContent=$('lessonTaskDisplay').value==='excluded'?'選択した授業を通知に戻す':'選択した授業を未記録通知から除外';root.querySelectorAll('[data-task-select]').forEach(el=>el.checked=selected.has(el.dataset.taskSelect));}
function draw(){
 if(admin)$('lessonTaskPeriodError').textContent=$('lessonTaskFrom').value&&$('lessonTaskUntil').value&&$('lessonTaskFrom').value>$('lessonTaskUntil').value?'終了日は開始日以降にしてください。':'';
 const rows=filtered().sort(taskOrder);for(const key of selected.keys())if(!rows.some(r=>r.key===key&&r.token===selected.get(key)))selected.delete(key);
 for(const id of ['lessonTaskBadge','recordsPendingBadge']){const badge=document.getElementById(id);if(badge){badge.textContent=mineCount??'';badge.hidden=!mineCount;badge.setAttribute('aria-label','自分の担当の未記録 '+(mineCount??0)+'件');}}
 $('lessonTaskCount').textContent=(admin&&$('lessonTaskDisplay').value==='excluded'?'除外済み':'未記入のある授業')+' ／ 表示対象 '+rows.length+'件';
 $('lessonTaskList').innerHTML=rows.slice(0,limit).map(r=>{
 const day=['日','月','火','水','木','金','土'][new Date(r.date+'T00:00:00').getDay()];
 return `<article class="lesson-task-card ${r.excluded?'task-excluded':''}" data-lesson-task="${esc(r.key)}"><div class="lesson-task-info">${admin?`<label class="task-select"><input type="checkbox" data-task-select="${esc(r.key)}" ${selected.has(r.key)?'checked':''}>${esc(r.date)} ${esc(r.slots)} ${esc(r.className)}を選択</label>`:''}<p class="lesson-task-meta">${esc(r.date)}（${day}） · ${esc(r.slots)} ${r.groupId?'連結':''}</p><h3><button type="button" class="task-class-link" data-task-class="${esc(r.className)}">${esc(r.className)}</button></h3><p class="lesson-task-meta">${esc(r.start)}–${esc(r.end)} · ${esc(r.room||'教室未設定')} · ${esc(r.teacher||'担当未設定（管理者）')}</p>${r.missing.includes('attendance')?'<small>出欠未登録：'+r.attendanceStudents+'名</small>':''}${r.excluded?'<p class="lesson-task-meta">通知から除外：'+esc(r.excludedBy)+' · '+esc(new Date(r.excludedAt).toLocaleString('ja-JP'))+'</p>':''}</div><div class="lesson-task-actions">${Object.keys(labels).map(m=>r.missing.includes(m)?`<a class="ws-button" data-record-task="${m}" href="${esc(r.url+'&recordTask='+m+(m==='attendance'?'&attendance=1':'')+'&fromNotice=1')}"><span class="task-missing-dot" aria-hidden="true"></span>${actions[m]} →</a>`:`<span class="lesson-task-complete">✓ ${m==='attendance'?'出欠':m==='memo'?'カルテ':'宿題'} 記録済み</span>`).join('')}</div></article>`;
 }).join('')||'<p class="ws-muted">条件に合う授業はありません。</p>';
 $('lessonTaskMore').hidden=rows.length<=limit;selection();
}
function options(id,values){const el=$(id),old=el.value;el.innerHTML='<option value="">すべて</option>'+values.map(([v,t])=>`<option value="${esc(v)}">${esc(t)}</option>`).join('');el.value=old;if(el.selectedIndex<0)el.value='';}
async function refresh(){
 if(!active||busy)return;const seq=++request;$('lessonTaskMessage').textContent='読み込み中…';
 try{const scope=$('lessonTaskScope').value,j=await Workspace.api('lesson_tasks_api.php?scope='+scope+(admin?'&includeExcluded=1':''));if(seq!==request)return;if(!Array.isArray(j.items))throw Error('通知の応答を確認できませんでした。');items=j.items;version=j.exclusionVersion||'';
 if(scope==='mine')mineCount=j.count;else{const own=await Workspace.api('lesson_tasks_api.php?countOnly=1');if(seq!==request)return;mineCount=own.count;}
 if(admin){options('lessonTaskTeacher',[...new Set(items.map(r=>r.teacher))].sort().map(v=>[v||'__unset__',v||'担当未設定']));}options('lessonTaskClass',[...new Set(items.map(r=>r.className))].sort().map(v=>[v,v]));draw();$('lessonTaskMessage').textContent='';
 }catch(e){if(seq===request)$('lessonTaskMessage').textContent='再読み込みしてください：'+e.message;}
}
async function deferSelected(){
 if(busy||!selected.size)return;const field=$('lessonTaskKind').value,fields=field?[field]:Object.keys(labels);busy=true;selection();const accepted=await new Promise(resolve=>{const d=document.createElement('dialog');d.className='task-tbd-dialog';d.setAttribute('aria-label','未定として記録する確認');d.innerHTML='<form method="dialog"><h2>未定として記録</h2><p>'+selected.size+'件の授業の'+esc(field?labels[field]:'未記入項目すべて')+'を「未定」で記録します。</p><p>入力済みの内容は上書きしません。後から授業の詳細で変更できます。</p><footer><button class="ws-button" value="cancel">キャンセル</button><button class="ws-button primary" value="confirm" autofocus>未定で記録する</button></footer></form>';d.addEventListener('close',()=>{const yes=d.returnValue==='confirm';d.remove();resolve(yes);},{once:true});document.body.append(d);d.showModal();});if(!accepted){busy=false;selection();return;}
 busy=true;++request;root.querySelectorAll('input,select,button').forEach(e=>e.disabled=true);try{await Workspace.api('lesson_tasks_api.php',{action:'set_tbd',version,fields,items:[...selected].map(([key,token])=>({key,token}))});selected.clear();busy=false;await refresh();Workspace.refreshRequestNotices();$('lessonTaskMessage').textContent='未記入項目を「未定」で記録しました。授業の詳細から、決まった内容へ変更できます。';}catch(e){$('lessonTaskMessage').textContent=e.message;}finally{busy=false;root.querySelectorAll('input,select,button').forEach(e=>e.disabled=false);selection();}
}
async function apply(){
 if(busy||!selected.size)return;const excluded=$('lessonTaskDisplay').value!=='excluded',count=selected.size;
 if(!confirm(count+'件を'+(excluded?'未記録通知から除外':'通知に戻し')+'しますか？\n出欠・カルテ・宿題の内容は変更しません。'))return;
 busy=true;++request;root.querySelectorAll('input,select,button').forEach(e=>e.disabled=true);$('lessonTaskMessage').textContent='保存中…';
 try{await Workspace.api('lesson_tasks_api.php',{action:'set_excluded',version,excluded,items:[...selected].map(([key,token])=>({key,token}))});selected.clear();busy=false;await refresh();Workspace.refreshRequestNotices();$('lessonTaskMessage').textContent=count+'件を'+(excluded?'未記録通知から除外しました。':'通知に戻しました。');}
 catch(e){$('lessonTaskMessage').textContent=e.message;}
 finally{busy=false;root.querySelectorAll('input,select,button').forEach(e=>e.disabled=false);selection();}
}
StaffAuth.ready.then(async({user})=>{
 if(!user)return;await Workspace.ready;active=true;admin=user.role==='admin';root.hidden=false;
 root.innerHTML=`<h2>未記録を確認 <span id="lessonTaskBadge" class="notice-count" hidden></span></h2><p class="ws-muted"><strong>${esc(user.name)}の担当${admin?'＋担当未設定':'のみ'}</strong>。赤い件数は終了した授業の数です（連結は1件）。</p><details class="lesson-task-filter"><summary>絞り込み・表示対象</summary><div class="ws-controls"><label ${admin?'':'hidden'}>対象<select id="lessonTaskScope"><option value="mine">${admin?'自分の担当・担当未設定':'自分の担当'}</option>${admin?'<option value="all">全講師（管理者）</option>':''}</select></label><label>未記入の種類<select id="lessonTaskKind"><option value="">すべて</option>${Object.entries(labels).map(([v,s])=>`<option value="${v}">${s}</option>`).join('')}</select></label><label>授業を探す<input id="lessonTaskSearch" type="search" placeholder="クラス・先生・日付"></label>${admin?'<label>開始日<input id="lessonTaskFrom" type="date"></label><label>終了日<input id="lessonTaskUntil" type="date"></label><label>担当講師<select id="lessonTaskTeacher"></select></label>':''}<button id="lessonTaskReload" class="ws-button">再読み込み</button></div></details>${admin?'<div class="task-bulk"><label>表示<select id="lessonTaskDisplay"><option value="active">未記録通知の対象</option><option value="excluded">除外済み（元に戻す）</option></select></label><div class="task-bulk-actions"><button id="lessonTaskSelectAll" class="ws-button">検索結果をすべて選択</button><button id="lessonTaskClear" class="ws-button">選択を解除</button><span id="lessonTaskSelected"></span><button id="lessonTaskTbd" class="ws-button">選択した未記入項目を「未定」で記録</button><button id="lessonTaskApply" class="ws-button" disabled>選択した授業を未記録通知から除外</button></div><small>除外すると講師・管理者の通知と赤い件数から外れます。実際の出欠・カルテ・宿題は変えず、ここから元に戻せます。</small></div>':''}<p id="lessonTaskMessage" class="ws-message" role="status"></p><div class="ws-controls"><label>授業の並び順<select id="lessonTaskSort"><option value="desc">新しい順</option><option value="asc">古い順</option></select></label><label>授業で絞る<select id="lessonTaskClass"><option value="">すべて</option></select></label><button type="button" id="lessonTaskClassClear" class="ws-button">授業の絞り込みを解除</button><p id="lessonTaskCount" aria-live="polite"></p></div><div id="lessonTaskList" class="lesson-task-list"></div><button id="lessonTaskMore" class="ws-button" hidden>さらに20件表示</button><p class="ws-muted">宿題を出さない日は「宿題なし」を保存してください。</p>`;
 if(admin){const area=document.createElement('section');area.className='task-period';area.setAttribute('aria-label','期間を指定して一括操作');area.innerHTML='<strong>① 対象・期間・種類で絞る → ② すべて選択・個別ON/OFF → ③ 未定で記録</strong><div class="ws-controls"></div><p id="lessonTaskPeriodError" role="status"></p>';root.querySelector('.lesson-task-filter').before(area);for(const id of ['lessonTaskScope','lessonTaskFrom','lessonTaskUntil','lessonTaskKind'])area.querySelector('.ws-controls').append($(id).closest('label'));}
 $('lessonTaskScope').onchange=()=>{selected.clear();limit=20;items=[];draw();refresh();};
 for(const id of ['lessonTaskKind','lessonTaskSearch','lessonTaskClass',...(admin?['lessonTaskFrom','lessonTaskUntil','lessonTaskTeacher','lessonTaskDisplay']:[])])$(id).addEventListener('input',()=>{selected.clear();limit=20;draw();});
 $('lessonTaskList').addEventListener('click',e=>{const b=e.target.closest('[data-task-class]');if(!b)return;$('lessonTaskClass').value=b.dataset.taskClass;selected.clear();limit=20;draw();});$('lessonTaskClassClear').onclick=()=>{$('lessonTaskClass').value='';selected.clear();limit=20;draw();};$('lessonTaskSort').onchange=()=>{limit=20;draw();};$('lessonTaskMore').onclick=()=>{limit+=20;draw();};$('lessonTaskReload').onclick=()=>{refresh();Workspace.refreshRequestNotices();};
 if(admin){$('lessonTaskSelectAll').onclick=()=>{const rows=filtered();if(rows.length>300){$('lessonTaskMessage').textContent='300件以内になるように日付や担当で絞り込んでください。';return;}selected=new Map(rows.map(r=>[r.key,r.token]));selection();};$('lessonTaskClear').onclick=()=>{selected.clear();selection();};$('lessonTaskApply').onclick=apply;$('lessonTaskTbd').onclick=deferSelected;$('lessonTaskList').onchange=e=>{const key=e.target.dataset.taskSelect;if(!key)return;const item=items.find(r=>r.key===key);if(e.target.checked)selected.set(key,item.token);else selected.delete(key);selection();};}refresh();
}).catch(e=>{root.hidden=false;root.textContent='未記入の通知を読み込めませんでした：'+e.message;});
window.addEventListener('pageshow',refresh);window.addEventListener('focus',refresh);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh();});document.addEventListener('lesson-recording-saved',refresh);setInterval(()=>{if(!document.hidden)refresh();},60000);
})();
