(()=>{'use strict';const $=id=>document.getElementById(id),esc=Workspace.esc,params=new URLSearchParams(location.search);let data={events:[],schools:[]},limit=30;
const date=s=>new Date(s+'T00:00:00+09:00').toLocaleDateString('ja-JP',{timeZone:'Asia/Tokyo',year:'numeric',month:'numeric',day:'numeric',weekday:'short'});
const heading=r=>`<div class="ce-tags"><span>${r.kind==='notice'?'塾のお知らせ':esc(r.schoolName)}</span>${r.published&&!r.archived?'':'<span>管理者プレビュー</span>'}</div><h2>${esc(r.title)}</h2><p>${esc(date(r.startDate))}${r.endDate!==r.startDate?' 〜 '+esc(date(r.endDate)):''}</p>`;
function render(){const school=$('noticeSchool').value,day=$('noticeDate').value,q=$('noticeSearch').value.trim().toLocaleLowerCase(),list=data.events.filter(r=>(!school||r.kind==='notice'||r.schoolId===school)&&(!day||r.startDate<=day&&day<=r.endDate)&&(!q||(r.title+' '+r.body+' '+r.schoolName).toLocaleLowerCase().includes(q)));$('noticesList').innerHTML=list.slice(0,limit).map(r=>`<article class="ws-panel ce-notice-card">${heading(r)}<p class="ce-preview">${esc(r.body.slice(0,180))}</p><a class="ws-button" href="notices.html?id=${r.id}">${r.image?'画像・詳細を見る':'詳細を見る'}</a></article>`).join('')||'<p class="ws-panel">条件に合う学校行事・お知らせはありません。</p>';$('noticesMore').hidden=list.length<=limit;$('noticesMessage').textContent=`${list.length}件中 ${Math.min(limit,list.length)}件を表示`;}
async function load(){try{await StaffAuth.ready;$('noticesManage').hidden=StaffAuth.user?.role!=='admin';const id=params.get('id');$('noticesManage').textContent=id?'行事の編集・学校登録':'閲覧表示に切り替え';if(StaffAuth.user?.role==='admin'&&!id){$('noticesAdmin').hidden=false;$('noticesBrowse').hidden=true;}if(id){$('noticesBrowse').hidden=true;const preview=params.has('preview')&&StaffAuth.user?.role==='admin';const j=await Workspace.api('calendar_events_api.php?id='+encodeURIComponent(id)+(preview?'&manage=1':'')),r=j.event;$('noticeDetail').hidden=false;$('noticeDetail').innerHTML=`<a class="ws-button" href="notices.html">← お知らせ一覧へ</a><article class="ws-panel">${heading(r)}${StaffAuth.user?.role==='admin'?'<button class="ws-button" id="noticeEdit" type="button">この行事・お知らせを編集</button>':''}<div class="ce-notice-body">${esc(r.body)}</div>${r.image?`<figure class="ce-notice-image"><a href="${esc(r.image.url)}" target="_blank" rel="noopener"><img src="${esc(r.image.url)}" alt="${esc(r.title)}のお知らせ画像"></a><figcaption>画像を押すと別画面で大きく表示します。</figcaption></figure>`:''}</article>`;$('noticesMessage').textContent='';$('noticeEdit')?.addEventListener('click',()=>SchoolEvents.edit(id));document.querySelector('#noticeDetail img')?.addEventListener('error',()=>{$('noticesMessage').textContent='画像を読み込めませんでした。ページを再読み込みしてください。';});return;}
 data=await Workspace.api('calendar_events_api.php');$('noticeSchool').innerHTML='<option value="">学校：すべて</option>'+data.schools.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('');$('noticeSchool').value=params.get('school')||'';$('noticeDate').value=params.get('date')||'';render();
 }catch(e){$('noticesMessage').textContent=e.message;$('noticesMessage').classList.add('error');}}
$('noticesManage').onclick=()=>{const manage=$('noticesAdmin').hidden;$('noticesAdmin').hidden=!manage;$('noticesBrowse').hidden=manage||params.has('id');$('noticeDetail').hidden=manage||!params.has('id');$('noticesManage').textContent=manage?'閲覧表示に切り替え':'行事の編集・学校登録';};document.addEventListener('calendar-events-saved',load);
for(const id of ['noticeSchool','noticeDate','noticeSearch'])$(id).addEventListener(id==='noticeSearch'?'input':'change',()=>{limit=30;render();});$('noticeClear').onclick=()=>{for(const id of ['noticeSchool','noticeDate','noticeSearch'])$(id).value='';limit=30;render();};$('noticesMore').onclick=()=>{limit+=30;render();};load();})();
