<?php require_once __DIR__.'/admin_page_guard.php'; requireAdminPage('payroll.html'); $payrollExcludedNames=staffSiteSettings(true)['payrollExcludedNames']; ?>
<!doctype html>
<html lang="ja">
<head><script src="staff-auth.js?v=20260917-r56-ready" data-staff="required"></script><script src="workspace-ui.js?v=20260916-r54-ready"></script>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>給与計算</title>
<style>
:root{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI","Noto Sans JP",sans-serif;color:#172033;background:#f5f7fb}*{box-sizing:border-box}body{margin:0}header{background:#fff;border-bottom:1px solid #dfe5ee;padding:14px 20px;display:flex;align-items:center;justify-content:space-between;gap:12px;position:sticky;top:0;z-index:10}h1{font-size:21px;margin:2px 0}header small{color:#667085}a{color:#2563eb}.wrap{max-width:1380px;margin:18px auto;padding:0 14px}.panel{background:#fff;border:1px solid #dfe5ee;border-radius:12px;padding:14px;margin-bottom:14px;box-shadow:0 2px 8px #12203a0a}.controls{display:flex;flex-wrap:wrap;gap:10px;align-items:end}.controls label{display:grid;gap:5px;font-size:13px;font-weight:700}.controls input,.controls select,.rate-form input,.rate-form select{min-height:38px;border:1px solid #cfd7e3;border-radius:8px;padding:7px 9px;background:#fff}button{min-height:38px;border:1px solid #c7d0de;border-radius:8px;background:#fff;padding:7px 12px;font-weight:700;cursor:pointer}.primary{background:#2457d6;color:#fff;border-color:#2457d6}.danger{color:#b42318}.summary{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:10px}.card{border:1px solid #e1e7ef;border-radius:10px;padding:12px}.card .value{font-size:25px;font-weight:800;margin-top:3px}.muted{color:#667085}.category-cards{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.chip{background:#f4f7fb;border:1px solid #dbe3ee;border-radius:999px;padding:6px 10px;font-size:13px}.tablewrap{overflow:auto}table{width:100%;border-collapse:collapse;white-space:nowrap}th,td{border-bottom:1px solid #e5e9f0;padding:8px 9px;text-align:left;font-size:13px}th{background:#f8fafc;position:sticky;top:0}td.num,th.num{text-align:right}.missing{background:#fff3cd;color:#7a4b00;font-weight:700}.rate-note{font-size:13px;color:#667085;margin:7px 0 12px}.status{font-size:13px;margin-left:8px}.rate-input{width:110px;min-height:34px;border:1px solid #cfd7e3;border-radius:7px;padding:5px 8px;text-align:right}.savebar{display:flex;gap:10px;align-items:center;margin:10px 0;position:sticky;top:72px;background:#fff;padding:8px 0;z-index:3}.paircount{font-size:13px;color:#667085}.right{margin-left:auto}.teacher-summary{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:10px}.teacher-card{border:1px solid #e1e7ef;border-radius:10px;padding:12px}.teacher-card b{font-size:15px}.teacher-card .money{font-size:22px;font-weight:800;margin-top:4px}.detail-box summary{cursor:pointer;font-weight:800;font-size:16px;padding:2px 0 10px}.detail-box[open] summary{margin-bottom:6px}@media(max-width:760px){header{align-items:flex-start;flex-direction:column}.controls>*{flex:1 1 140px}.right{margin-left:0}.savebar{top:104px}}
.lesson-link{background:transparent;border:0;padding:4px 0;text-align:left;color:#2457b3;text-decoration:underline;text-underline-offset:3px;white-space:normal}.lesson-link:hover{color:#103e95}.payroll-dialog{border:0;border-radius:14px;padding:0;width:min(800px,94vw);max-height:88dvh;color:#172033}.payroll-dialog::backdrop{background:#172d4670}.payroll-dialog-inner{display:flex;flex-direction:column;max-height:88dvh}.payroll-dialog header{position:static;flex:none}.payroll-dialog h2{font-size:18px;margin:0}.payroll-dialog-body{padding:16px;overflow:auto}.payroll-lesson{display:flex;gap:16px;justify-content:space-between;padding:12px 0;border-top:1px solid #dfe5ee;font-size:14px}.payroll-lesson p{margin:5px 0;color:#526477}.payroll-lesson a{display:block;padding:8px 0}.payroll-lesson>div{min-width:0;overflow-wrap:anywhere}@media(max-width:600px){.payroll-lesson{flex-direction:column;gap:0}.payroll-dialog header{flex-direction:row}}
</style>
<link rel="stylesheet" href="workspace-ui.css?v=20260912-r24"></head>
<body>
<header><div><small>進学教室 志学館</small><h1>給与計算</h1></div><div><a href="schedule_generator.html">時間割データ生成へ戻る</a></div></header>
<div class="wrap"><p class="r45-build" style="font-size:11px;color:#607080;margin:4px 0;text-align:right">更新版 r45</p>
<section class="panel controls">
<label>開始日<input id="from" type="date"></label><label>終了日<input id="to" type="date"></label>
<label>講師<select id="teacher"><option value="">すべて</option></select></label>
<button id="thisMonth">今月</button><button id="prevMonth">前月</button><button id="calc" class="primary">再計算</button><span id="status" class="status"></span>
</section>
<section class="panel"><div class="summary"><div class="card"><div class="muted" id="totalKomaLabel">対象コマ数</div><div class="value" id="totalKoma">0</div></div><div class="card"><div class="muted" id="totalPayLabel">給与総計</div><div class="value" id="totalPay">¥0</div></div><div class="card"><div class="muted">単価未設定コマ</div><div class="value" id="missingCount">0</div></div></div><p id="payrollScopeNote" class="rate-note"></p><div id="categorySummary" class="category-cards"></div></section>
<section class="panel"><h2 style="font-size:17px;margin:0 0 8px">単価設定（授業名 × 先生）</h2><div class="rate-note"><b>入力はここだけです。</b> 同じ授業名・同じ先生のコマはすべて同じ単価になります。例：中3総合 × 担当の先生 = 2,000円。期間内に20コマあれば自動で40,000円です。授業名を押すと、この期間の授業詳細を表示します。</div><div class="savebar"><button id="saveAllRates" class="primary">単価をまとめて保存</button><span id="pairCount" class="paircount"></span></div><div class="tablewrap"><table><thead><tr><th>授業名</th><th>先生</th><th>区分</th><th class="num">コマ数</th><th class="num">1コマ単価</th><th class="num">給与小計</th></tr></thead><tbody id="ratePairs"></tbody></table></div></section>
<section class="panel"><h2 style="font-size:17px;margin:0 0 10px">先生別集計</h2><div id="teacherSummary" class="teacher-summary"></div></section>
<section class="panel detail-box"><details><summary>コマ明細を表示（確認用）</summary><div class="tablewrap"><table><thead><tr><th>日付</th><th>時間</th><th>講師</th><th>授業名</th><th>給与区分</th><th class="num">単価</th><th class="num">給与</th></tr></thead><tbody id="detail"></tbody></table></div></details></section>
</div>
<dialog id="payrollLessons" class="payroll-dialog" aria-labelledby="payrollLessonsTitle"><div class="payroll-dialog-inner"><header><h2 id="payrollLessonsTitle">授業詳細</h2><button type="button" id="payrollLessonsClose">閉じる</button></header><div class="payroll-dialog-body"><p id="payrollLessonsPeriod"></p><p class="rate-note">詳細は別タブで開きます。この画面で入力中の単価は残ります。給与は連結前のコマ数で計算します。</p><div id="payrollLessonsList"></div></div></div></dialog>
<script>
(()=>{'use strict';
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let rows=[],rates=[],groups=[];const excludedFromTotal=new Set(<?= json_encode($payrollExcludedNames,JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT) ?>); const CATS=['演習','小学生','中学生','高校生','その他'];
const norm=s=>String(s??'').trim();
const pairKey=(teacher,cls)=>norm(teacher)+'\u0001'+norm(cls);
const normDate=s=>{const m=String(s||'').replaceAll('-','/').match(/(\d{4})\/(\d{1,2})\/(\d{1,2})/);return m?`${m[1]}-${m[2].padStart(2,'0')}-${m[3].padStart(2,'0')}`:''};
function inferCat(r){const explicit=norm(r['給与区分']);if(CATS.includes(explicit))return explicit;const type=norm(r['種別']),cls=norm(r['クラス']);if(type==='演習')return '演習';if(/^小|小学/.test(cls))return '小学生';if(/^中|中学/.test(cls))return '中学生';if(/^高|高校/.test(cls))return '高校生';return 'その他'}
function uniq(field){return [...new Set(rows.map(r=>norm(r[field])).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ja',{numeric:true}))}
function fill(){const teachers=uniq('担当講師');$('teacher').innerHTML='<option value="">すべて</option>'+teachers.map(x=>`<option>${esc(x)}</option>`).join('')}
function exactRate(teacher,cls){const t=norm(teacher),c=norm(cls);const matches=rates.filter(q=>norm(q.teacher)===t&&norm(q.class)===c);if(!matches.length)return null;const plain=matches.find(q=>!norm(q.category));const x=plain||matches[0];const n=Number(x.amount);return Number.isFinite(n)&&n>=0?n:null}
function fallbackRate(r){const t=norm(r['担当講師']),c=norm(r['クラス']),cat=inferCat(r);const exact=exactRate(t,c);if(exact!==null)return exact;const levels=[['',cat],['','']];for(const [cl,ca] of levels){const x=rates.find(q=>norm(q.teacher)===t&&norm(q.class)===cl&&norm(q.category)===ca);if(x){const n=Number(x.amount);if(Number.isFinite(n)&&n>=0)return n}}return null}
function filtered(){const f=$('from').value,t=$('to').value,teacher=$('teacher').value;return rows.filter(r=>{const d=normDate(r['日付']);if(!d||norm(r['日区分']))return false;if(f&&d<f)return false;if(t&&d>t)return false;if(teacher?norm(r['担当講師'])!==teacher:excludedFromTotal.has(norm(r['担当講師'])))return false;return !!norm(r['担当講師'])})}
function lessonUrl(r){
 const group=groups.find(g=>g.sources.includes(r._sourceKey));
 if(group)return 'lesson_group.html?'+new URLSearchParams({v:'20260916-r53',id:group.id});
 const key=[normDate(r['日付']),norm(r['時間番号']),norm(r['クラス']),norm(r['担当講師']),norm(r['種別']),norm(r['科目']).split(/[,、，]/).map(norm).filter(Boolean).join('+')].join('|');
 return 'teacher2026summer_vertical.html?'+new URLSearchParams({teacher:norm(r['担当講師']),date:normDate(r['日付']),openKey:key});
}
function openClass(cls,teacher){
 const arr=filtered().filter(r=>norm(r['クラス'])===cls&&norm(r['担当講師'])===teacher).sort((a,b)=>(normDate(a['日付'])+norm(a['開始'])).localeCompare(normDate(b['日付'])+norm(b['開始'])));
 const d=$('payrollLessons');$('payrollLessonsTitle').textContent=cls+' ／ '+teacher;
 $('payrollLessonsPeriod').textContent=$('from').value+' ～ '+$('to').value+' ／ '+arr.length+'コマ分';
 // Display a linked lesson once, but retain every original slot in its pay calculation.
 const units=new Map();for(const r of arr){const url=lessonUrl(r);if(!units.has(url))units.set(url,[]);units.get(url).push(r);}
 $('payrollLessonsList').innerHTML=[...units.entries()].map(([url,rs])=>{const first=rs[0],last=rs[rs.length-1],amounts=rs.map(fallbackRate),missing=amounts.some(v=>v===null),pay=amounts.reduce((sum,v)=>sum+(v||0),0);return `<article class="payroll-lesson"><div><b>${esc(normDate(first['日付']))} ${esc(rs.map(r=>r['時間番号']).join(''))}</b><p>${esc(first['開始'])}–${esc(last['終了'])} ／ ${esc(first['教室']||'教室未設定')}${rs.length>1?' ／ 連結':''}</p></div><div>${rs.length}コマ分・${missing?'単価未設定':'¥'+pay.toLocaleString()}<a href="${esc(url)}" target="_blank" rel="noopener">授業詳細を開く ↗</a></div></article>`;}).join('')||'<p>対象の授業はありません。</p>';
 d.showModal();
}
function groupPairs(arr){const map=new Map();for(const r of arr){const teacher=norm(r['担当講師']),cls=norm(r['クラス']);if(!teacher||!cls)continue;const k=pairKey(teacher,cls);if(!map.has(k))map.set(k,{teacher,cls,cat:inferCat(r),count:0});map.get(k).count++}return [...map.values()].sort((a,b)=>a.teacher.localeCompare(b.teacher,'ja',{numeric:true})||a.cls.localeCompare(b.cls,'ja',{numeric:true}))}
function renderRatePairs(arr){const pairs=groupPairs(arr);$('pairCount').textContent=`${arr.length}コマ → ${pairs.length}種類の「授業名×先生」に集約`;$('ratePairs').innerHTML=pairs.length?pairs.map((p,i)=>{const rate=exactRate(p.teacher,p.cls);const pay=rate===null?null:rate*p.count;return `<tr data-teacher="${esc(p.teacher)}" data-class="${esc(p.cls)}"><td><button type="button" class="lesson-link" data-payroll-class="${esc(p.cls)}" data-payroll-teacher="${esc(p.teacher)}">${esc(p.cls)}</button></td><td>${esc(p.teacher)}</td><td>${esc(p.cat)}</td><td class="num">${p.count}</td><td class="num"><input class="rate-input" data-rate-input="1" type="number" min="0" step="10" value="${rate===null?'':rate}" placeholder="未設定"></td><td class="num pair-pay">${pay===null?'—':'¥'+pay.toLocaleString()}</td></tr>`}).join(''):'<tr><td colspan="6" class="muted">対象データなし</td></tr>';
$('ratePairs').querySelectorAll('[data-rate-input]').forEach(inp=>inp.addEventListener('input',()=>{const tr=inp.closest('tr');const count=Number(tr.children[3].textContent)||0;const v=inp.value===''?null:Number(inp.value);tr.querySelector('.pair-pay').textContent=v===null||!Number.isFinite(v)?'—':'¥'+Math.round(v*count).toLocaleString()}))}
function calc(){const reference=excludedFromTotal.has($('teacher').value);$('totalKomaLabel').textContent=reference?'参考コマ数':'対象コマ数';$('totalPayLabel').textContent=reference?'参考額（給与総計の対象外）':'給与総計';$('payrollScopeNote').textContent=reference?`${$('teacher').value}先生の単価と参考額を表示しています。この金額は給与総計には含めません。`:(excludedFromTotal.size?`${[...excludedFromTotal].join('・')}先生は一覧・給与総計に含めません。単価の設定や確認は、講師欄で対象の先生を選んでください。`:'すべての講師を給与総計に含めます。');const a=filtered().sort((x,y)=>(normDate(x['日付'])+norm(x['開始'])).localeCompare(normDate(y['日付'])+norm(y['開始'])));let total=0,missing=0;const cats=Object.fromEntries(CATS.map(c=>[c,0])),ts=new Map();$('detail').innerHTML=a.map(r=>{const cat=inferCat(r),rate=fallbackRate(r),teacher=norm(r['担当講師']);cats[cat]=(cats[cat]||0)+1;if(!ts.has(teacher))ts.set(teacher,{count:0,total:0,missing:0});const t=ts.get(teacher);t.count++;if(rate===null){missing++;t.missing++}else{total+=rate;t.total+=rate}return `<tr><td>${esc(normDate(r['日付']).replaceAll('-','/'))}</td><td>${esc(r['時間番号']||'')} ${esc(r['開始']||'')}-${esc(r['終了']||'')}</td><td>${esc(teacher)}</td><td><a href="${esc(lessonUrl(r))}" target="_blank" rel="noopener" title="授業詳細を別タブで開く">${esc(r['クラス'])}</a></td><td>${esc(cat)}${!r['給与区分']?' <span class="muted">(自動)</span>':''}</td><td class="num ${rate===null?'missing':''}">${rate===null?'未設定':'¥'+rate.toLocaleString()}</td><td class="num">${rate===null?'—':'¥'+rate.toLocaleString()}</td></tr>`}).join('')||'<tr><td colspan="7" class="muted">対象データなし</td></tr>';$('totalKoma').textContent=a.length.toLocaleString();$('totalPay').textContent='¥'+total.toLocaleString();$('missingCount').textContent=missing.toLocaleString();$('categorySummary').innerHTML=CATS.map(c=>`<span class="chip">${c} ${cats[c]||0}コマ</span>`).join('');$('teacherSummary').innerHTML=[...ts.entries()].sort((a,b)=>a[0].localeCompare(b[0],'ja')).map(([name,v])=>`<div class="teacher-card"><b>${esc(name)}</b><div class="money">¥${v.total.toLocaleString()}</div><div class="muted">${v.count}コマ${v.missing?` ／ 未設定 ${v.missing}コマ`:''}</div></div>`).join('')||'<div class="muted">対象データなし</div>';renderRatePairs(a)}
async function saveRates(){const res=await fetch('payroll_api.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({rates})});const j=await res.json().catch(()=>({}));if(!res.ok||!j.ok)throw new Error(j.error||'保存失敗');rates=j.rates||rates;$('status').textContent='単価を保存しました';calc()}
async function saveAllVisibleRates(){const visible=[];$('ratePairs').querySelectorAll('tr[data-teacher]').forEach(tr=>{const teacher=tr.dataset.teacher,cls=tr.dataset.class,inp=tr.querySelector('[data-rate-input]');if(!inp||inp.value==='')return;const amount=Number(inp.value);if(!Number.isFinite(amount)||amount<0)return;visible.push({teacher,cls,amount})});const keys=new Set(visible.map(x=>pairKey(x.teacher,x.cls)));rates=rates.filter(r=>!keys.has(pairKey(r.teacher,r.class)));for(const x of visible)rates.push({teacher:x.teacher,class:x.cls,category:'',amount:x.amount});try{await saveRates()}catch(e){alert(e.message)}}
function month(offset=0){const d=new Date();d.setDate(1);d.setMonth(d.getMonth()+offset);const y=d.getFullYear(),m=d.getMonth();const last=new Date(y,m+1,0).getDate(),pad=n=>String(n).padStart(2,'0');$('from').value=`${y}-${pad(m+1)}-01`;$('to').value=`${y}-${pad(m+1)}-${pad(last)}`;calc()}
async function load(){try{const [d,p,g]=await Promise.all([fetch('data_api.php?v='+Date.now(),{cache:'no-store'}),fetch('payroll_api.php?v='+Date.now(),{cache:'no-store'}),fetch('lesson_group_api.php?action=index',{cache:'no-store'})]);const dj=await d.json(),pj=await p.json(),gj=await g.json();if(!d.ok||!dj.ok)throw new Error(dj.error||'時間割読込失敗');if(!p.ok||!pj.ok)throw new Error(pj.error||'単価読込失敗');if(!g.ok||!gj.ok)throw new Error(gj.error||'連結情報の読込失敗');rows=dj.schedule||[];rates=pj.rates||[];groups=gj.groups||[];fill();month(0);$('status').textContent=`時間割 ${rows.length}件を読込`;}catch(e){$('status').textContent='読込エラー: '+e.message}}
$('ratePairs').addEventListener('click',e=>{const b=e.target.closest('[data-payroll-class]');if(b)openClass(b.dataset.payrollClass,b.dataset.payrollTeacher);});$('payrollLessonsClose').onclick=()=>$('payrollLessons').close();$('payrollLessons').addEventListener('click',e=>{if(e.target===$('payrollLessons')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});$('calc').onclick=calc;$('teacher').onchange=calc;$('from').onchange=calc;$('to').onchange=calc;$('thisMonth').onclick=()=>month(0);$('prevMonth').onclick=()=>month(-1);$('saveAllRates').onclick=saveAllVisibleRates;load();
})();
</script>
<script src="admin-page-cache.js?v=20260910-r5"></script></body></html>
