(()=>{'use strict';const $=id=>document.getElementById(id),esc=Workspace.esc,dialog=$('calendarEditor');let data={schools:[],events:[]},busy=false,dirty=false,previewUrl='',loaded=false;
async function request(payload){
 let response,body;try{response=await fetch(payload?'calendar_events_api.php':'calendar_events_api.php?manage=1',payload instanceof FormData?{method:'POST',body:payload}:payload?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}:{cache:'no-store'});body=await response.text();}catch(e){throw Error('通信に失敗しました。入力内容は残しています。一覧を確認してから再度お試しください。（CE_NETWORK）');}
 let j;try{j=JSON.parse(body);}catch(e){throw Error('サーバーから'+(body.trim()?'正常な応答が返りませんでした。':'応答が返りませんでした。')+'入力内容は残しています。保存された可能性もあるため、別のタブで一覧を確認してください。（CE_HTTP_'+response.status+(body.trim()?'_FORMAT':'_EMPTY')+'）');}
 if(!response.ok||!j||j.ok!==true)throw Error(j?.error||'処理を完了できませんでした。入力内容は残しています。（CE_HTTP_'+response.status+'）');return j;
}
const categories={test:'テスト',trip:'修学旅行・校外学習',festival:'文化祭・体育祭',closure:'休講・休校のお知らせ',announcement:'塾のお知らせ',other:'その他'};
const token=()=>[...crypto.getRandomValues(new Uint8Array(16))].map(n=>n.toString(16).padStart(2,'0')).join('');
const opts=(map,value)=>Object.entries(map).map(([k,v])=>`<option value="${esc(k)}" ${k===value?'selected':''}>${esc(v)}</option>`).join('');
function message(s,error=false){$('calendarMessage').textContent=s;$('calendarMessage').classList.toggle('error',error);}
function msg(s,error=false){$('ceEditorMessage').textContent=s;$('ceEditorMessage').classList.toggle('error',error);}
function lock(v){busy=v;dialog.querySelectorAll('input,select,textarea,button').forEach(e=>e.disabled=v);}
function close(){if(busy||dirty&&!confirm('入力中の内容を保存せずに閉じますか？'))return;dialog.close();dirty=false;if(previewUrl){URL.revokeObjectURL(previewUrl);previewUrl='';}}
function shell(title){dialog.innerHTML=`<div class="ce-dialog-layout"><div class="ce-dialog-head"><h2 id="ceEditorTitle">${esc(title)}</h2><button id="ceEditorClose" class="ws-button" type="button">閉じる</button></div><div class="ce-dialog-body"><form id="ceEditorForm" class="ws-form"></form></div><div class="ce-dialog-foot"><span id="ceEditorMessage" class="ws-message" role="status"></span><button id="ceEditorSave" class="ws-button primary" form="ceEditorForm" type="submit">保存</button></div></div>`;$('ceEditorClose').onclick=close;dirty=false;dialog.showModal();$('ceEditorForm').oninput=$('ceEditorForm').onchange=()=>{dirty=true;};}
function render(){
 const schools=data.schools.filter(s=>$('schoolArchived').checked||!s.archived);$('schoolList').innerHTML=schools.map(s=>`<div class="ce-school-row ${s.archived?'ce-muted':''}"><span>${esc(s.name)}${s.archived?'（非表示）':''}</span><button class="ws-button" data-school-edit="${s.id}">編集</button></div>`).join('')||'<p class="ws-muted">学校は未登録です。「学校を登録」から追加してください。</p>';
 const q=$('calendarSearch').value.trim().toLocaleLowerCase(),kind=$('calendarKind').value;
 const events=data.events.filter(e=>($('calendarArchived').checked||!e.archived)&&(!kind||e.kind===kind)&&(!q||(e.title+' '+e.schoolName).toLocaleLowerCase().includes(q)));
 $('calendarManageList').innerHTML=events.map(e=>`<article class="ce-manage-row ${e.archived?'ce-muted':''}"><div><div class="ce-tags"><span>${e.kind==='notice'?'塾のお知らせ':esc(e.schoolName)}</span><span>${e.archived?'非表示':e.published?'公開中':'下書き'}</span>${e.image?'<span>画像あり</span>':''}</div><h3>${esc(e.title)}</h3><p>${esc(e.startDate)} 〜 ${esc(e.endDate)}</p></div><div class="ce-row-actions"><button class="ws-button" data-event-edit="${e.id}">編集</button><a class="ws-button" href="notices.html?id=${e.id}${e.published&&!e.archived?'':'&preview=1'}">${e.published&&!e.archived?'表示を見る':'プレビュー'}</a></div></article>`).join('')||'<p class="ws-muted">条件に合う行事・お知らせはありません。</p>';
}
async function load(){message('読み込み中…');$('schoolNew').disabled=$('calendarNew').disabled=true;try{const j=await request();data=j;loaded=true;render();message('');return true;}catch(e){loaded=false;message(e.message,true);return false;}finally{$('schoolNew').disabled=$('calendarNew').disabled=!loaded;}}
function schoolEditor(s=null){if(!loaded)return;shell(s?'学校を編集':'学校を登録');const form=$('ceEditorForm');form.innerHTML=`<label>学校名（必須）<input name="name" maxlength="200" required value="${esc(s?.name||'')}" placeholder="例：豊中市立○○中学校"></label><label class="ws-check"><input name="archived" type="checkbox" ${s?.archived?'checked':''}>この学校を非表示にする</label><p class="ws-muted">非表示の学校の行事は予定表にも表示されません。学校名を変更しても、旧学校名で登録した生徒との対応は引き継ぎます。</p>`;form.onsubmit=async e=>{e.preventDefault();if(busy)return;const fields={action:'school_save',id:s?.id||'',version:s?.version||'',name:form.elements.name.value,archived:form.elements.archived.checked};lock(true);msg('保存中…');try{await request(fields);dirty=false;dialog.close();await load();}catch(err){msg(err.message,true);}finally{lock(false);}};form.elements.name.focus();}
function eventEditor(old=null){if(!loaded)return;const today=new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Tokyo'}),r=old||{kind:'school',schoolId:'',category:'test',title:'',startDate:today,endDate:today,body:'',published:false,archived:false},requestId=token();shell(old?'行事・お知らせを編集':'行事・お知らせを登録');const form=$('ceEditorForm');
 form.innerHTML=`<label>登録するもの<select name="kind">${opts({school:'学校行事',notice:'塾のお知らせ'},r.kind)}</select></label><label id="ceSchoolField">学校（必須）<select name="schoolId"><option value="">学校を選択してください</option>${data.schools.filter(s=>!s.archived||s.id===r.schoolId).map(s=>`<option value="${s.id}" ${s.id===r.schoolId?'selected':''}>${esc(s.name)}${s.archived?'（非表示）':''}</option>`).join('')}</select><small>候補がないときは、先に学校一覧で登録してください。</small></label><label>行事の種類<select name="category">${opts(categories,r.category)}</select></label><label>件名（必須）<input name="title" maxlength="120" required value="${esc(r.title)}" placeholder="例：中間テスト、修学旅行、シルバーウィークのお知らせ"></label><div class="ce-form-grid"><label>開始日（必須）<input name="startDate" type="date" required value="${esc(r.startDate)}"></label><label>終了日（必須）<input name="endDate" type="date" required value="${esc(r.endDate)}"></label></div><label>説明<textarea name="body" maxlength="10000" rows="5">${esc(r.body)}</textarea></label><label>お知らせ画像<input name="image" type="file" accept="image/jpeg,image/png,image/webp"><small>JPEG・PNG・WebP、5MB以下。サーバーの設定により上限が小さい場合があります。</small></label><div id="ceImagePreview">${r.image?`<img src="${esc(r.image.url)}" alt="現在のお知らせ画像">`:''}</div>${r.image?'<label class="ws-check"><input name="removeImage" type="checkbox">現在の画像を外す</label>':''}<label class="ws-check ce-public-choice"><input name="published" type="checkbox" ${r.published?'checked':''}>予定表・お知らせページに公開する</label><p class="ws-muted">公開すると生徒・保護者・先生が閲覧できます。学校行事は生徒の所属学校に合わせて表示し、塾のお知らせは全員に表示します。授業の削除や休講設定は変更しません。</p><label class="ws-check"><input name="archived" type="checkbox" ${r.archived?'checked':''}>非表示にする（記録は残す）</label>`;
 const schoolField=()=>{$('ceSchoolField').hidden=form.elements.kind.value!=='school';form.elements.schoolId.required=form.elements.kind.value==='school';};schoolField();form.elements.kind.onchange=()=>{schoolField();dirty=true;};
 form.elements.startDate.onchange=()=>{if(form.elements.endDate.value<form.elements.startDate.value)form.elements.endDate.value=form.elements.startDate.value;dirty=true;};
 form.elements.image.onchange=()=>{dirty=true;if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl='';const file=form.elements.image.files[0];if(file){if(file.size>5*1024*1024){msg('画像は5MB以下にしてください。',true);form.elements.image.value='';return;}previewUrl=URL.createObjectURL(file);$('ceImagePreview').innerHTML=`<img src="${previewUrl}" alt="選択した画像のプレビュー">`;}};
 form.onsubmit=async e=>{e.preventDefault();if(busy||!form.reportValidity())return;const fd=new FormData(form),payload={action:'event_save',id:r.id||'',version:r.version||'',requestId};for(const k of ['kind','schoolId','category','title','startDate','endDate','body'])payload[k]=fd.get(k)||'';for(const k of ['published','archived','removeImage'])payload[k]=fd.get(k)==='on';const body=new FormData();body.set('payload',JSON.stringify(payload));const file=form.elements.image.files[0];if(file)body.set('image',file);lock(true);msg('保存中…');try{await request(body);dirty=false;dialog.close();if(previewUrl){URL.revokeObjectURL(previewUrl);previewUrl='';}await load();}catch(err){msg(err.message,true);}finally{lock(false);}};form.elements.title.focus();
}
$('schoolNew').onclick=()=>schoolEditor();$('calendarNew').onclick=()=>eventEditor();$('calendarReload').onclick=load;$('calendarSearch').oninput=render;for(const id of ['schoolArchived','calendarArchived','calendarKind'])$(id).onchange=render;
$('schoolList').onclick=e=>{const b=e.target.closest('[data-school-edit]');if(b)schoolEditor(data.schools.find(s=>s.id===b.dataset.schoolEdit));};$('calendarManageList').onclick=e=>{const b=e.target.closest('[data-event-edit]');if(b)eventEditor(data.events.find(r=>r.id===b.dataset.eventEdit));};
dialog.oncancel=e=>{e.preventDefault();close();};dialog.onclick=e=>{if(e.target!==dialog)return;const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close();};window.addEventListener('beforeunload',e=>{if(dirty&&dialog.open){e.preventDefault();e.returnValue='';}});StaffAuth.ready.then(load);
})();
