(()=>{'use strict';const contexts=new WeakMap(),esc=Workspace.esc;let counts={};const token=()=>[...crypto.getRandomValues(new Uint8Array(16))].map(n=>n.toString(16).padStart(2,'0')).join('');
async function request(url,payload){
 let r,body;try{r=await fetch(url,payload?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}:{cache:'no-store'});body=await r.text();}catch(e){throw Error('共有メモの通信に失敗しました。入力は残しています。接続を確認して再読み込みしてください。（SN_NETWORK）');}
 let j;try{j=JSON.parse(body);}catch(e){if(r.status===404)throw Error('共有メモのプログラムが見つかりません。管理者が差分ZIPの shared_notes_api.php をアップロードしてください。（SN_HTTP_404）');throw Error((body.trim()?'共有メモから正常なデータが返っていません。':'共有メモの応答が空でした。')+'入力は残しています。管理者にこの表示をお知らせください。（SN_HTTP_'+r.status+(body.trim()?'_FORMAT':'_EMPTY')+'）');}
 if(!r.ok||!j||j.ok!==true)throw Error(j?.error||'共有メモを読み込めませんでした。入力は残しています。（SN_HTTP_'+r.status+'）');
 if(!url.includes('summary=')&&(!Array.isArray(j.notes)||j.notes.some(n=>!n||typeof n.id!=='string'||typeof n.text!=='string'||!Array.isArray(n.completionHistory))))throw Error('共有メモのデータ形式を確認できません。上書きせず入力を残しています。管理者にお知らせください。（SN_FORMAT）');
 return j;
}
const date=v=>v?new Date(v).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit',weekday:'short',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}):'記録なし';
function actions(n){return `<div class="shared-note-actions"><label class="shared-note-check"><input type="checkbox" data-note-todo="${esc(n.id)}" ${n.todo?'checked':''} ${!n.canManage||n.done?'disabled data-shared-readonly':''}>TODO</label>${n.todo?`<strong class="shared-note-assignee">担当：${esc(n.assignees.map(a=>a.name).join('・')||'未設定')}</strong><button type="button" class="ws-button" data-note-done="${esc(n.id)}" ${n.canComplete?'':'disabled data-shared-readonly'}>${n.done?'未完了に戻す':'完了'}</button>`:`<label class="shared-note-check"><input type="checkbox" data-note-done="${esc(n.id)}" ${n.done?'checked':''}>${n.done?'非表示中':'非表示'}</label>`}${n.unread?`<button type="button" class="ws-button" data-note-read="${esc(n.id)}">確認しました</button>`:''}</div>`;}
function draw(c){if(!c.list.isConnected)return;c.list.innerHTML=c.notes.filter(n=>c.showHidden||!n.done).map(n=>`<article class="shared-note ${n.todo?'is-todo':''} ${n.done?'is-done':''}">${actions(n)}<div class="shared-note-text">${esc(n.text)}</div><div class="shared-note-meta">${n.legacy?'以前の共有メモ（発言者・発言日時の記録なし）':esc(n.author)+' ／ '+esc(date(n.createdAt))}</div>${n.done?`<p class="shared-note-completed">${n.todo?'完了':'非表示'}：${esc(n.doneBy)} ／ ${esc(date(n.doneAt))}</p>`:''}${n.completionHistory.length?`<details class="shared-note-history"><summary>完了・表示変更の履歴</summary>${n.completionHistory.map(h=>`<p>${h.done?(n.todo?'完了':'非表示'):'再表示'}：${esc(h.by)} ／ ${esc(date(h.at))}</p>`).join('')}</details>`:''}</article>`).join('')||'<p class="ws-muted">表示中の共有メモはありません。</p>';counts[c.cls]=c.notes.filter(n=>!n.done).length;}
function notify(){document.dispatchEvent(new Event('shared-notes-changed'));Workspace.refreshRequestNotices();}
async function refresh(c){
 if(c.loading)return c.loading;
 c.loaded=false;c.error='';c.status.textContent='共有メモを読み込み中…';c.list.querySelectorAll('input').forEach(e=>e.disabled=true);
 const promise=(async()=>{try{const j=await request('shared_notes_api.php?className='+encodeURIComponent(c.cls));if(contexts.get(c.input)!==c)return false;c.notes=j.notes;if(j.staff){const el=c.toolbar.querySelector('.shared-note-target'),old=el.value;el.innerHTML='<option value="auto">このクラスの担当講師（未設定は管理者）</option>'+j.staff.map(u=>'<option value="'+esc(u.id)+'">'+esc(u.name)+'</option>').join('');el.value=old||'auto';}c.loaded=true;draw(c);c.status.textContent='';return true;}catch(e){c.error=e.message;if(contexts.get(c.input)===c)c.status.textContent=e.message+(c.notes.length?' 最後に読み込んだ一覧を表示しています。':'');return false;}finally{c.loading=null;}})();c.loading=promise;return promise;
}
function mount(input,cls){if(!input)return;const old=contexts.get(input);if(old){old.list.remove();old.toolbar.remove();}input.value='';input.placeholder='新しい共有メモを入力（ログインした先生の名前・日時で記録）';input.maxLength=10000;
 const list=document.createElement('div');list.className='shared-notes-list';input.before(list);const toolbar=document.createElement('div');toolbar.className='shared-notes-toolbar';toolbar.innerHTML='<button type="button" class="shared-notes-reload">共有メモを再読み込み</button><label><input type="checkbox" class="shared-notes-show-hidden"> 非表示も表示</label><a href="shared_todos.html">TODO一覧</a><span class="shared-notes-status" role="status"></span><div class="shared-note-compose"><label><input class="shared-note-new-todo" type="checkbox">TODOとして投稿</label><label class="shared-note-target-wrap" hidden>担当<select class="shared-note-target" aria-label="TODOの担当"><option value="auto">このクラスの担当講師（未設定は管理者）</option></select></label></div>';list.before(toolbar);
 const c={input,list,toolbar,status:toolbar.querySelector('span'),cls:Workspace.className(cls),notes:[],showHidden:false,requestId:token(),loaded:false,loading:null,error:'',pending:null,toggling:false};contexts.set(input,c);toolbar.querySelector('button').onclick=()=>{if(!c.pending&&!c.toggling)refresh(c);};
 toolbar.addEventListener('input',e=>e.stopPropagation());toolbar.addEventListener('change',e=>e.stopPropagation());
 toolbar.querySelector('.shared-notes-show-hidden').onchange=e=>{c.showHidden=e.target.checked;draw(c);};
 c.toolbar.querySelector('.shared-note-new-todo').onchange=e=>{c.toolbar.querySelector('.shared-note-target-wrap').hidden=!e.target.checked;c.requestId=token();};c.toolbar.querySelector('.shared-note-target').onchange=()=>c.requestId=token();input.addEventListener('input',()=>{if(contexts.get(input)===c)c.requestId=token();});
 async function change(e){const control=e.target.closest('[data-note-done],[data-note-todo],[data-note-read]');if(!control||(control.tagName==='INPUT'&&e.type!=='change')||(control.tagName!=='INPUT'&&e.type!=='click'))return;e.stopPropagation();const id=control.dataset.noteDone||control.dataset.noteTodo||control.dataset.noteRead,n=c.notes.find(n=>n.id===id);if(!n)return;const action=control.hasAttribute('data-note-todo')?'todo':control.hasAttribute('data-note-read')?'read':'done',todo=action==='todo'?control.checked:!!n.todo;draw(c);if(!c.loaded||c.loading||c.toggling||c.pending)return;c.toggling=true;c.list.querySelectorAll('input,button').forEach(el=>el.disabled=true);c.status.textContent='保存中…';try{const j=await request('shared_notes_api.php',{action,className:c.cls,id:n.id,version:n.version,...(action==='todo'?{todo}:action==='done'?{done:!n.done}:{})});if(contexts.get(input)!==c)return;c.notes=j.notes;draw(c);c.status.textContent='保存しました。';notify();}catch(err){c.status.textContent=err.message;draw(c);}finally{c.toggling=false;}}
 list.onchange=change;list.onclick=change;refresh(c);
}
async function post(cls,input){const c=contexts.get(input);if(c?.pending)return c.pending;if(!input?.value.trim())return true;if(!c||c.cls!==Workspace.className(cls))throw Error('クラスが変更されています。入力中の共有メモを控えてから詳細を開き直し、新しいクラスへ投稿してください。');if(!c.loaded&&!await refresh(c))throw Error(c.error||'共有メモを読み込めません。入力は残しています。');if(contexts.get(input)!==c)throw Error('共有メモのクラスが変わりました。開いている詳細を確認してください。');if(c.pending)return c.pending;const text=input.value.trim(),todo=c.toolbar.querySelector('.shared-note-new-todo').checked,target=c.toolbar.querySelector('.shared-note-target').value;if(!text)return true;if(c.toggling)throw Error('表示状態の保存後にもう一度お試しください。');
 const promise=(async()=>{c.status.textContent='発言を保存中…';try{const j=await request('shared_notes_api.php',{action:'post',className:c.cls,text,todo,assigneeIds:target==='auto'?null:[target],requestId:c.requestId});c.requestId=token();if(contexts.get(input)===c){c.notes=j.notes;draw(c);if(input.value.trim()===text)input.value='';c.status.textContent='発言者と日時を記録しました。';notify();}return true;}catch(e){c.status.textContent=e.message;throw e;}finally{c.pending=null;}})();c.pending=promise;return promise;
}
// Parent lesson dialogs also unlock their form controls after loading. Keep note permissions intact.
const protect=()=>document.querySelectorAll('[data-shared-readonly]').forEach(e=>{if(!e.disabled)e.disabled=true;});
const protectStart=()=>{protect();new MutationObserver(protect).observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['disabled']});};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',protectStart);else protectStart();
window.SharedNotes={mount,post,hasNotes:cls=>!!counts[Workspace.className(cls)],busy:input=>{const c=contexts.get(input);return !!(c?.pending||c?.toggling);}};StaffAuth.ready.then(j=>{if(j.user)request('shared_notes_api.php?summary=1').then(j=>{counts=j.counts;}).catch(()=>{});});
})();
