<?php
// Called by the authenticated shared-notes API, under the existing atomic-write lock.
function snStaff(){static $staff=null;if($staff===null){$staff=[];foreach(staffAccounts() as $id=>$u)if(!empty($u['active']))$staff[]=['id'=>(string)$id,'name'=>$u['name'],'role'=>$u['role']];}return $staff;}
function snClassRecipients($class){static $classes=null;if($classes===null){$classes=[];foreach(policyRows() as $r){$cls=snClass($r['クラス']??'');$date=str_replace('/','-',$r['日付']??'');if($cls!==''&&empty($r['日区分']))$classes[$cls][]=[$date,trim($r['担当講師']??'')];}}$rows=$classes[$class]??[];$future=array_values(array_filter($rows,fn($r)=>$r[0]>=date('Y-m-d')));if($future)$rows=$future;elseif($rows){$last=max(array_column($rows,0));$rows=array_values(array_filter($rows,fn($r)=>$r[0]===$last));}$names=array_unique(array_column($rows,1));$ids=[];foreach(snStaff() as $u)if(in_array($u['name'],$names,true)||((!$names||in_array('',$names,true))&&$u['role']==='admin'))$ids[]=$u['id'];if(!$ids)foreach(snStaff() as $u)if($u['role']==='admin')$ids[]=$u['id'];return $ids;}
function snTargets($in,$class){$ids=$in['assigneeIds']??null;if($ids===null)return snClassRecipients($class);if(!is_array($ids)||!$ids||count($ids)>100)staffFail('担当者を選んでください。',400);$valid=array_column(snStaff(),'id');foreach($ids as $id)if(!is_string($id)||!in_array($id,$valid,true))staffFail('担当者が変更されています。再読み込みしてください。',400);return array_values(array_unique($ids));}
function snMine($r){global $actor;return in_array($actor['id'],$r['recipientIds']??[],true);}
function snCanManage($r){global $actor;return $actor['role']==='admin'||($r['authorId']??'')===$actor['id'];}
function snExtraProjection($r){global $actor;$r['todo']=!empty($r['todo']);$r['mine']=snMine($r);$r['unread']=$r['mine']&&empty($r['done'])&&empty($r['reads'][$actor['id']]);$r['canComplete']=$actor['role']==='admin'||!$r['todo']||$r['mine'];$r['canManage']=snCanManage($r);$staff=array_column(snStaff(),null,'id');$r['assignees']=array_map(fn($id)=>['id'=>$id,'name'=>$staff[$id]['name']??($r['recipientNames'][$id]??'以前の担当者')],$r['recipientIds']??[]);return $r;}
function snInbox(){global $data;$items=[];foreach($data['notes'] as $r){$r['className']=snClass($r['className']);$items[]=snProjection($r);}return $items;}
function snRecipientNames($ids){$names=[];foreach(snStaff() as $u)if(in_array($u['id'],$ids,true))$names[$u['id']]=$u['name'];return $names;}
