(()=>{'use strict';
const root=document.getElementById('sharedTodoList')||document.getElementById('sharedNotesInbox');if(!root)return;
const todo=!!document.getElementById('sharedTodoList'),esc=Workspace.esc,date=v=>v?new Date(v).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'}):'記録なし';let data=null,busy=false,ticket=0,started=false;
const $=id=>root.querySelector('#'+id);
function selected(){const q=$('snFind').value.trim().toLocaleLowerCase(),from=$('snFrom').value,until=$('snUntil').value,assignee=$('snAssignee').value,status=$('snState').value;if(from&&until&&from>until){$('snMessage').textContent='終了日は開始日以降にしてください。';return [];}$('snMessage').textContent='';return data.items.filter(r=>(!todo||r.todo)&&(assignee==='all'||(r.recipientIds||[]).includes(assignee))&&(!q||[r.text,r.className,r.author,...r.assignees.map(a=>a.name)].join(' ').toLocaleLowerCase().includes(q))&&(!from||(r.createdAt||'').slice(0,10)>=from)&&(!until||(r.createdAt||'').slice(0,10)<=until)&&(status==='all'||status==='done'&&r.done||status==='open'&&!r.done||status==='unread'&&r.unread)).sort((a,b)=>($('snOrder').value==='asc'?1:-1)*((a.createdAt||'').localeCompare(b.createdAt||'')||a.id.localeCompare(b.id)));}
function draw(){if(!data)return;const rows=selected();$('snCount').textContent=rows.length+'件';$('snCards').innerHTML=rows.map(r=>`<article class="shared-note ${r.todo?'is-todo':''} ${r.done?'is-done':''}" data-sn-id="${esc(r.id)}"><div class="shared-note-actions"><strong>${r.todo?'TODO':'共有メモ'} · ${esc(r.className)}</strong>${r.unread?'<b class="sn-unread">未読</b>':''}<span>担当：${esc(r.assignees.map(a=>a.name).join('・')||'以前のメモ（担当指定なし）')}</span></div><p class="shared-note-text">${esc(r.text)}</p><p class="shared-note-meta">${esc(r.author||'記録なし')} ／ ${esc(date(r.createdAt))}</p>${r.done?'<p class="shared-note-completed">'+(r.todo?'完了':'非表示')+'：'+esc(r.doneBy)+' ／ '+esc(date(r.doneAt))+'</p>':''}<div class="shared-note-actions">${r.todo?'<button type="button" class="ws-button" data-sn-action="done" '+(r.canComplete?'':'disabled data-sn-readonly')+'>'+(r.done?'未完了に戻す':'完了')+'</button>':''}${r.unread?'<button type="button" class="ws-button" data-sn-action="read">確認しました</button>':''}<a class="ws-button" href="${esc(Workspace.classLink(r.className))}">この授業の予定</a></div>${r.completionHistory.length?'<details class="shared-note-history"><summary>完了・表示変更の履歴</summary>'+r.completionHistory.map(h=>'<p>'+esc(h.by)+' ／ '+esc(date(h.at))+' ／ '+(h.done?'完了・非表示':'未完了・再表示')+'</p>').join('')+'</details>':''}</article>`).join('')||'<p class="ws-muted">該当する'+(todo?'TODO':'共有メモ')+'はありません。</p>';}
async function load(){if(!started||busy)return;const seq=++ticket;$('snMessage').textContent='読み込み中…';try{const j=await Workspace.api('shared_notes_api.php?inbox=1');if(seq!==ticket)return;data=j;const sel=$('snAssignee'),old=sel.value;sel.innerHTML='<option value="'+esc(StaffAuth.user.id)+'">自分の担当</option><option value="all">全担当</option>'+j.staff.filter(u=>u.id!==StaffAuth.user.id).map(u=>'<option value="'+esc(u.id)+'">'+esc(u.name)+'</option>').join('');sel.value=old||StaffAuth.user.id;draw();}catch(e){$('snMessage').textContent=e.message;}}
StaffAuth.ready.then(async({user})=>{if(!user)return;await Workspace.ready;root.hidden=false;started=true;root.innerHTML=`${todo?'':'<h2>自分宛ての先生共有メモ</h2><p>新しい共有メモを確認できます。<a href="shared_todos.html">TODO一覧へ</a></p>'}<div class="ws-controls"><label>検索<input id="snFind" type="search" placeholder="授業・内容・投稿者"></label><label>担当<select id="snAssignee"></select></label><label>状態<select id="snState">${todo?'':'<option value="unread">未読</option>'}<option value="open">未完了・表示中</option><option value="done">完了・非表示</option><option value="all">すべて</option></select></label><label>投稿日から<input id="snFrom" type="date"></label><label>投稿日まで<input id="snUntil" type="date"></label><label>並び順<select id="snOrder"><option value="asc">古い順（昇順）</option><option value="desc" ${todo?'':'selected'}>新しい順（降順）</option></select></label><button id="snReload" type="button" class="ws-button">再読み込み</button></div><p id="snMessage" class="ws-message" role="status"></p><p id="snCount"></p><div id="snCards" class="sn-cards"></div>`;
for(const id of ['snFind','snAssignee','snState','snFrom','snUntil','snOrder'])$(id).oninput=draw;$('snReload').onclick=load;
$('snCards').onclick=async e=>{const button=e.target.closest('[data-sn-action]');if(!button||busy)return;const item=data.items.find(r=>r.id===button.closest('[data-sn-id]').dataset.snId);if(!item)return;busy=true;root.querySelectorAll('button,input,select').forEach(x=>x.disabled=true);try{await Workspace.api('shared_notes_api.php',{action:button.dataset.snAction,className:item.className,id:item.id,version:item.version,done:!item.done});busy=false;await load();document.dispatchEvent(new Event('shared-notes-changed'));Workspace.refreshRequestNotices();}catch(err){$('snMessage').textContent=err.message;}finally{busy=false;root.querySelectorAll('button,input,select').forEach(x=>x.disabled=x.hasAttribute('data-sn-readonly'));}};load();});
window.addEventListener('focus',load);document.addEventListener('shared-notes-changed',load);document.addEventListener('visibilitychange',()=>{if(!document.hidden)load();});setInterval(()=>{if(!document.hidden)load();},60000);
})();
