(()=>{
const $=id=>document.getElementById(id),esc=Workspace.esc;let busy=false;
function dialog(title){let d=$('studentEditDialog');if(!d){d=document.createElement('dialog');d.id='studentEditDialog';d.className='ws-dialog directory-dialog';document.body.appendChild(d);}d.innerHTML=`<div class="ws-dialog-inner"><div class="ws-dialog-head"><h2>${esc(title)}</h2><button id="studentEditClose" class="ws-button">閉じる</button></div><div id="studentEditBody" class="ws-dialog-body"></div><div class="ws-dialog-foot"><span id="studentEditMessage" class="ws-message" role="status"></span><button id="studentEditSave" class="ws-button primary">変更を保存</button></div></div>`;d.oncancel=e=>{if(busy)e.preventDefault();};$('studentEditClose').onclick=()=>{if(!busy)d.close();};return d;}
function msg(text,error=false){$('studentEditMessage').textContent=text;$('studentEditMessage').classList.toggle('error',error);}
function pending(value){busy=value;$('studentEditDialog').querySelectorAll('button,input,select').forEach(el=>el.disabled=value);}
async function refreshList(){await Workspace.refresh();document.dispatchEvent(new Event('student-management-updated'));}
async function memberships(name){
 const d=dialog(name+'の参加クラスの設定');d.showModal();pending(true);msg('読み込み中…');
 let data,date=Workspace.today(),draft=new Map(),initial=new Map(),newClasses=new Set();
 try{data=await Workspace.api('student_manage_api.php?action=memberships&name='+encodeURIComponent(name));await Workspace.refresh();}catch(e){msg(e.message,true);pending(false);$('studentEditSave').disabled=true;return;}
 const stateAt=(r,day)=>!Workspace.enrolled(r,day,true)?'ended':(r['免除期間']||[]).some(p=>(!p.from||p.from<=day)&&(!p.until||day<p.until))?'exempt':StudentParticipation.freeAt(r,day)?'optional':'active';
 function reset(){initial=new Map(data.rows.map(r=>[r['クラス'],stateAt(r,date)]));draft=new Map(initial);newClasses=new Set();}
 reset();
 $('studentEditBody').innerHTML=`<label class="ws-form">適用日<input type="date" id="studentMembershipDate" value="${date}"></label><p class="ws-muted">適用日以降を変更します。以前の出席・カルテは残ります。「自由参加」は、参加は自由ですが、講師は参加を勧めています。同じ時間に優先度の高い授業があれば、その授業を予定表に表示します。優先度が同じなら両方を表示します。「免除」は生徒の予定から外し、出席未入力の通知も対象外にします。すでに入力した各コマの出席は優先します。</p><div id="studentMembershipRows"></div><section class="ws-panel"><h3>参加クラスを追加</h3><div class="ws-controls"><select id="studentAddClass" aria-label="追加するクラス">${data.classes.sort((a,b)=>a.localeCompare(b,'ja')).map(c=>`<option>${esc(c)}</option>`).join('')}</select><button id="studentAddExistingClass" class="ws-button">選んだクラスを追加</button></div><p class="ws-muted">新しいクラスもここで作成できます。保存するまで追加されません。</p><div class="ws-controls"><input id="studentNewClass" type="text" maxlength="100" placeholder="新しいクラス名" aria-label="新しいクラス名"><button id="studentAddNewClass" class="ws-button">新規クラスを追加</button></div></section>`;
 function render(){ $('studentMembershipRows').innerHTML=[...draft].map(([c,status])=>`<div class="student-membership-row"><strong>${esc(c)}${newClasses.has(c)?'<span class="directory-badge">新規</span>':''}</strong><select data-student-class="${esc(c)}" aria-label="${esc(c)}の参加状態">${[['active','参加'],['optional','自由参加'],['exempt','このクラスを免除'],['ended','参加終了']].map(([v,l])=>`<option value="${v}" ${status===v?'selected':''}>${l}</option>`).join('')}</select></div>`).join('')||'<p>参加クラスはありません。</p>';}
 $('studentMembershipRows').onchange=e=>{if(e.target.dataset.studentClass)draft.set(e.target.dataset.studentClass,e.target.value);};
 $('studentMembershipDate').onchange=e=>{const dirty=newClasses.size||[...draft].some(([c,s])=>s!==initial.get(c));if(dirty&&!confirm('日付を変更すると未保存の編集を取り消します。変更しますか？')){e.target.value=date;return;}date=e.target.value;reset();render();};
 $('studentAddExistingClass').onclick=()=>{const c=$('studentAddClass').value;if(c){draft.set(c,'active');render();}};
 $('studentAddNewClass').onclick=()=>{const c=$('studentNewClass').value.trim();if(!c)return;if(data.classes.includes(c)||Workspace.className(c)!==c){msg('同じクラス名、または旧名が使われています。既存のクラスから選んでください。',true);return;}draft.set(c,'active');newClasses.add(c);$('studentNewClass').value='';msg('下書きに追加しました。最後に変更を保存してください。');render();};
 $('studentEditSave').onclick=async()=>{const changes=[...draft].filter(([c,s])=>newClasses.has(c)||s!==initial.get(c)).map(([className,status])=>({className,status,create:newClasses.has(className)}));if(!changes.length){msg('変更はありません。');return;}pending(true);msg('保存中…');try{await Workspace.api('student_manage_api.php',{action:'memberships',name,date,version:data.version,changes});await refreshList();d.close();$('studentManageMessage').textContent=name+'の参加クラスの設定を保存しました。';}catch(e){msg(e.message,true);}finally{pending(false);}};
 pending(false);msg('');render();
}
async function lessons(name){
 const d=dialog(name+'の授業ごとの免除');$('studentEditSave').hidden=true;
 let from=Workspace.today(),rows=[];
 $('studentEditBody').innerHTML=`<div class="ws-controls"><label>開始日<input type="date" id="studentLessonsFrom" value="${from}"></label><button id="studentLessonsLoad" class="ws-button">14日分を表示</button><button id="studentLessonsPrev" class="ws-button">前の14日</button><button id="studentLessonsNext" class="ws-button">次の14日</button></div><p class="ws-muted">ボタンを押した時点で、この生徒・このコマだけに保存します。クラス設定で免除中でも、このコマだけ解除できます。</p><div id="studentLessonRows"></div>`;
 async function load(){pending(true);msg('読み込み中…');try{from=$('studentLessonsFrom').value;const end=new Date(from+'T00:00:00');end.setDate(end.getDate()+13);const j=await Workspace.api('student_manage_api.php?action=lessons&name='+encodeURIComponent(name)+'&from='+from+'&to='+end.toLocaleDateString('sv-SE'));rows=j.lessons||[];$('studentLessonRows').innerHTML=rows.map((r,i)=>`<article class="directory-row"><div class="directory-info"><strong>${esc(r.date)} ${esc(r.slot)} ${esc(r.className)}</strong><div class="ws-muted">${esc(r.start)}–${esc(r.end)} / ${esc(r.teacher)} / 出席：${esc(r.attendance)}</div></div><button class="ws-button" data-student-lesson="${i}">${r.exempt?'免除を解除':'このコマを免除'}</button></article>`).join('')||'<p class="directory-empty">この期間の参加授業はありません。</p>';msg('');}catch(e){msg(e.message,true);}finally{pending(false);}}
 $('studentLessonsLoad').onclick=load;for(const [id,days] of [['studentLessonsPrev',-14],['studentLessonsNext',14]])$(id).onclick=()=>{const day=new Date($('studentLessonsFrom').value+'T00:00:00');day.setDate(day.getDate()+days);$('studentLessonsFrom').value=day.toLocaleDateString('sv-SE');load();};
 $('studentLessonRows').onclick=async e=>{const b=e.target.closest('[data-student-lesson]');if(!b||busy)return;const r=rows[Number(b.dataset.studentLesson)];if(!r.exempt&&!['未入力','免除（クラス設定）','---'].includes(r.attendance)&&!confirm('このコマの出席「'+r.attendance+'」を免除に変更しますか？'))return;pending(true);msg('保存中…');try{await Workspace.api('student_manage_api.php',{action:'exempt_lesson',name,sourceKey:r.sourceKey,version:r.version,exempt:!r.exempt});await load();msg('保存しました。');}catch(err){msg(err.message,true);}finally{pending(false);}};
 d.showModal();await load();
}
async function newClass(){const d=dialog('新しいクラスを作成');$('studentEditBody').innerHTML='<label class="ws-form">クラス名<input id="studentCreateClassName" type="text" maxlength="100" placeholder="新しいクラス名"></label><p class="ws-muted">参加生徒0人で作成します。作成後、各生徒の「参加クラス・免除」から追加できます。</p>';$('studentEditSave').textContent='クラスを作成';d.showModal();let version;try{version=(await Workspace.api('class_manage_api.php')).version;}catch(e){msg(e.message,true);$('studentEditSave').disabled=true;return;}$('studentEditSave').onclick=async()=>{pending(true);msg('保存中…');try{const name=$('studentCreateClassName').value.trim();await Workspace.api('class_manage_api.php',{action:'create',name,version,names:[],date:Workspace.today()});await refreshList();d.close();$('studentManageMessage').textContent=name+'を作成しました。';}catch(e){msg(e.message,true);}finally{pending(false);}};}
document.addEventListener('click',e=>{if(StaffAuth.user?.role!=='admin'||busy)return;const member=e.target.closest('[data-student-memberships]'),lesson=e.target.closest('[data-student-lessons]');if(member)memberships(member.dataset.studentMemberships);else if(lesson)lessons(lesson.dataset.studentLessons);else if(e.target.closest('#studentCreateClass'))newClass();});
})();
