(()=>{
window.WeekCopy={open:async(from,to)=>{
 let d=document.getElementById('weekCopyDialog');if(!d){d=document.createElement('dialog');d.id='weekCopyDialog';d.className='ws-dialog';document.body.appendChild(d);}
 const plan=await Workspace.api('week_copy_api.php?'+new URLSearchParams({from:Workspace.iso(from),to:Workspace.iso(to)}));const requestId=crypto.randomUUID();
 await LessonFixed.ready;const rows=Generator.rows(),target=rows.filter(r=>Workspace.iso(r['日付'])===Workspace.iso(to));const fixed=target.filter(r=>LessonFixed.isFixed(Generator.eventKey(r))).length;
 d.innerHTML=`<div class="ws-dialog-inner"><div class="ws-dialog-head"><h2>表示した日からコピー</h2><button id="weekCopyClose" class="ws-button">閉じる</button></div><div class="ws-dialog-body"><p>${Workspace.esc(from)} → ${Workspace.esc(to)}</p><p>コピー先には ${target.length}コマ（確定済み ${fixed}コマ）あります。</p><div class="ws-form"><label class="ws-check"><input type="radio" name="weekCopyMode" value="empty" checked>空き枠にだけ追加する</label><small class="ws-muted">作成済みの予定を残し、同じ教室が埋まっている枠は飛ばします。PC教室は複数配置できます。</small><label class="ws-check"><input type="radio" name="weekCopyMode" value="append">作成済みを残して追加する</label><small class="ws-muted">同じ内容の授業は飛ばし、他教室の同時利用は確認します。</small><label class="ws-check"><input type="radio" name="weekCopyMode" value="replace">確定済み以外をコピー元の内容で組み直す</label><small class="ws-muted">コピー先の確定していない予定を取り消してコピーします。過去のカルテ・出席は残し、確定済みの予定は維持します。</small></div></div><div class="ws-dialog-foot"><span id="weekCopyMessage" class="ws-message"></span><button id="weekCopyRun" class="ws-button primary">この方式でコピーする</button></div></div>`;
 d.querySelector('#weekCopyClose').onclick=()=>d.close();d.querySelector('#weekCopyRun').onclick=async e=>{const mode=d.querySelector('[name=weekCopyMode]:checked').value;if(mode==='replace'&&!confirm(`コピー先の確定していない ${target.length-fixed}コマを取り消して組み直します。実行しますか？`))return;e.target.disabled=true;try{const j=await Workspace.api('week_copy_api.php',{from:Workspace.iso(from),to:Workspace.iso(to),mode,version:plan.version,requestId});await LessonGroups.refresh();await Generator.reload();document.getElementById('status').textContent=`${j.copied}件コピー・${j.skipped}件スキップ・${j.removed}件取消（確定済み ${j.fixedPreserved}件を維持）`;d.close();}catch(err){d.querySelector('#weekCopyMessage').textContent=err.message;}finally{e.target.disabled=false;}};d.showModal();
}};
})();
