const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),path=require('path');
const source=fs.readFileSync(path.resolve(__dirname,'../student-homework-live.js'),'utf8');
const flush=()=>new Promise(resolve=>setImmediate(resolve));
async function client(){const listeners={},timers=new Map();let id=0,revision='a',calls=0,loads=0,fail=false,release=null;
 const document={visibilityState:'visible',addEventListener:(name,fn)=>listeners[name]=fn},window={addEventListener:(name,fn)=>listeners[name]=fn};
 const sandbox={document,window,navigator:{onLine:true},console:{warn(){}},queueMicrotask,Promise,setTimeout:(fn,ms)=>{timers.set(++id,{fn,ms});return id;},clearTimeout:id=>timers.delete(id),StudentSchedule:{ready:Promise.resolve(true),refreshHomework:async()=>{loads++;if(fail)throw Error('offline');}},fetch:async(url,options)=>{calls++;if(release)await release.promise;return options.headers['If-None-Match']===revision?{status:304}:{ok:true,status:200,json:async()=>({ok:true,revision})};}};
 window.StudentSchedule=sandbox.StudentSchedule;vm.runInNewContext(source,sandbox);await flush();return {window,document,listeners,timers,get calls(){return calls;},get loads(){return loads;},change:v=>revision=v,fail:v=>fail=v,gate(){let done;release={promise:new Promise(resolve=>done=resolve)};return ()=>{release=null;done();};}};
}
test('separate server revisions refresh, stable revisions avoid full downloads and back off',async()=>{const c=await client();assert.equal(c.loads,1);c.window.StudentHomeworkLive.check();await flush();assert.equal(c.loads,1);assert.ok(c.window.StudentHomeworkLive.status.delay>3000);c.change('b');c.window.StudentHomeworkLive.check();await flush();assert.equal(c.loads,2);assert.equal(c.window.StudentHomeworkLive.status.etag,'b');});
test('parallel wakes serialize and recheck newer revision after delayed response',async()=>{const c=await client();const release=c.gate();c.change('b');c.window.StudentHomeworkLive.check();c.window.StudentHomeworkLive.check();c.window.StudentHomeworkLive.check();assert.equal(c.calls,2);release();await flush();assert.equal(c.calls,3);assert.equal(c.loads,2);assert.equal(c.window.StudentHomeworkLive.status.busy,false);});
test('failed download retains old revision and retries; hidden tabs stop and resume',async()=>{const c=await client();c.change('b');c.fail(true);c.window.StudentHomeworkLive.check();await flush();assert.equal(c.window.StudentHomeworkLive.status.etag,'a');assert.equal(c.window.StudentHomeworkLive.status.failures,1);c.document.visibilityState='hidden';c.listeners.visibilitychange();assert.equal(c.timers.size,0);const calls=c.calls;c.window.StudentHomeworkLive.check();await flush();assert.equal(c.calls,calls);c.fail(false);c.document.visibilityState='visible';c.listeners.visibilitychange();await flush();assert.equal(c.window.StudentHomeworkLive.status.etag,'b');assert.equal(c.window.StudentHomeworkLive.status.failures,0);});
